### ISSUE TITLE
Would like to make the write_through parameter dynamic

### ISSUE THREAD

**Issue by storcium** [bvanassche/scst#1]
Please consider the following scenario for SCST host to host failover, where a target is expected to gracefully move from host A to host B:
1. Targets/LUs with write cache are disabled on host A and all initiator sessions are disconnected
2. All outstanding write cache data is flushed to backing device
3. Targets/LUs are started on host B

The write cache here must completely drain before step (3) can be initiated (otherwise we may have data going out of order and corrupting the backing device).  Since there may be a lot of data in write cache, the time interval between steps (2) and (3) can be significant.  In tests using HD Tune Pro and Iometer we were able to observe delays longer than ESXi initiator will accept, for example around 5 minutes to flush write cache completely (granted this had to be constant high load, but such situation are possible in production).  So the success of step (3) depends on the amount of data in write cache at the time of failover.

If dynamic write-through mode was possible, we would have:
1. All targets/LUs on host A are moved to write-through mode and take as long as they need to drain their write caches
2. Targets/LUs are disabled on host A and all initiator sessions are disconnected
3. Targets/LUs are started on host B (no wait)

In this latter scenario there is no possibility of write cache drain time affecting the success of failover.

The other scenario where a dynamic write-through/write-back cache transition may be very helpful is an operational process that requires a burst of I/O activity for a given period of time (such as a database bulk load).  This is a case well described in SCST README, where the granularity of data integrity is the entire operation.  In this case one would switch write-back cache on for the duration of the bulk load, then turn it off at the end to increase resilience of the system.

**Comment by bvanassche** [comment]
Please reopen if this ticket needs further attention.
