### ISSUE TITLE
I got error when I execute scstadmin

### ISSUE THREAD

**Issue by narangel** [bvanassche/scst#10]
Hi,
I installed scst on CentOS 6.8 and edited scst.conf file.
Then I got some error when I executed '#scstadmin -force -config /etc/scst.conf' as below.

[root@noname ~]# scstadmin -force -config /etc/scst.conf

Collecting current configuration: done.

-> Checking configuration file '/etc/scst.conf' for errors.
	-> WARNING: Device 'disk1' associated with driver/target 'copy_manager/copy_manager_tgt' at LUN 0 is not defined within configuration, removing it.

	-> WARNING: Device 'disk1' associated with driver/target 'qla2x00t/20:01:00:0e:1e:30:54:6e' at LUN 0 is not defined within configuration, removing it.

	-> WARNING: No LUN 0 defined for driver/target/group 'qla2x00t/20:01:00:0e:1e:30:54:6e/host1'. Many initiators require a LUN 0 to be defined.

	-> Done, 3 warnings found.

Performing this action may result in lost or corrupt data, are you sure you wish to continue (y/[n]) ? y
-> Applying configuration.

Collecting current configuration: done.

FATAL: Received the following error:

	Invalid configuration encountered. Attribute '       ' has an invalid value.

[root@noname ~]#

I don't know what is wrong.
my scst.conf file is as below.

[root@noname ~]# cat /etc/scst.conf
HANDLER vdisk_blockio {
        DEVICE disk1 {
                filename /dev/sdb
        }
}
HANDLER vdisk_fileio {
	DEVICE disk2 {
		filename /mnt/disk1
	}
}

TARGET_DRIVER copy_manager {
	TARGET copy_manager_tgt {
		LUN 0 disk1
		LUN 1 disk2
 	}
}
TARGET_DRIVER qla2x00t {
	TARGET 20:01:00:0e:1e:30:54:6e {
		enabled 1
		rel_tgt_id 1
		HW_TARGET
		GROUP host1 {
			LUN 0 disk1
  			LUN 1 disk2
			INITIATOR 20:01:00:0e:1e:d1:cc:bc

		}
	}
        TARGET 20:01:00:0e:1e:30:54:6f {
		enabled 0
		rel_tgt_id 2
		HW_TARGET
		GROUP host2 {
			LUN 0 disk1
			LUN 1 disk2

			INITIATOR 20:01:00:0e:1e:d1:cc:bd
		}
	}
}
[root@noname ~]#

anybody who can know what is wrong on above?

**Comment by bvanassche** [comment]
Can you either check your scst.conf file for weird characters with od -c or a hex editor or provide it by attaching it to this github issue?

**Comment by narangel** [comment]
I re-wrote the configuration with scstadmin and there is no error now on above command.
I just added 1 block device to scst.conf. This is my configuration now.

[root@noname ~]# cat /etc/scst.conf
# Automatically generated by SCST Configurator v3.2.0-pre1.


HANDLER vdisk_blockio {
	DEVICE disk1 {
		filename /dev/sdb
	}
}

TARGET_DRIVER copy_manager {
	TARGET copy_manager_tgt {
		LUN 0 disk1
	}
}

TARGET_DRIVER qla2x00t {
	TARGET 20:01:00:0e:1e:30:54:6e {
		HW_TARGET

		enabled 0
		rel_tgt_id 1

		GROUP group1 {
			LUN 0 disk1

			INITIATOR 20:01:00:0e:1e:d1:cc:bc

			INITIATOR 20:01:00:0e:1e:d1:cc:bd
		}
	}

	TARGET 20:01:00:0e:1e:30:54:6f {
		HW_TARGET

		enabled 0
		rel_tgt_id 2
	}
}
[root@noname ~]# scstadmin -force -config /etc/scst.conf

Collecting current configuration: done.

-> Checking configuration file '/etc/scst.conf' for errors.
	-> Done, 0 warnings found.

Performing this action may result in lost or corrupt data, are you sure you wish to continue (y/[n]) ? y
-> Applying configuration.

Collecting current configuration: done.

	-> Done, 0 change(s) made.

All done.
[root@noname ~]# service scst status
SCST status: OK
[root@noname ~]#

But I have another problem now. The problem is that there is no changes on initiator server.
I mean that the server what has both of "20:01:00:0e:1e:d1:cc:bc" and "20:01:00:0e:1e:d1:cc:bd".
Is there something to do on initiator server?
