### ISSUE TITLE
Does "SCST" work with SAN switch?

### ISSUE THREAD

**Issue by narangel** [bvanassche/scst#11]
Hi,
I am testing SCST on Centos 6.8 now.
It is working fine when I connected SCST server to client directly with FC cable.
And I was wondering whether it can be worked with SAN switch or now.
Then I tried to connect SCST server to client with Qlogic SANBOX 5800(4G SAN s/w) and it was not working. Of course, it was working when I changed the connection directly.

So, I want to know whether "SCST" can be working with SAN switch in theory or not.

**Comment by bvanassche** [comment]
(back from traveling)
Yes, SCST supports SAN switches. I'm not sure why there is an operability problem with the Qlogic SANBOX 5800.
