### ISSUE TITLE
About delete session

### ISSUE THREAD

**Issue by zlsh007** [bvanassche/scst#14]
Hi
I want to delete a session, I executed the cmd：
echo 1 > /sys/kernel/scst_tgt/targets/iscsi/117:1/sessions/iqn.1994-05.com.redhat/force_close
But it rebuilt a session. dmesg like this:
[https://github.com/zlsh007/Ohters/blob/master/debug](url)
Excuse me, is this operation missing something, or need another way to actually delete a session?
 
regards

**Comment by bvanassche** [comment]
Thank you for having shared the kernel messages. I think the messages that you shared mean that SCST closed the session and also that immediately after the session had been closed that the initiator decided to log in again. If you want to prevent that the initiator logs in again I think that you have to change the enabled attribute from 1 into 0. However, that approach has the disadvantage that it affects all initiators associated with a target port.

**Comment by zlsh007** [comment]
Yeah, thank you for your reply. I tried it. It works well，I just need
to disconnect all the initiators that connect to this target. :)

regards


Bart Van Assche <notifications@github.com> 于2019年1月25日周五 上午11:43写道：

**Comment by zlsh007** [comment]
I still have a question to consult, I can delete the session now, but
this scst still seems to have its lun device, a drbd device, I need to
stop this drbd device, but the operation drbdadm down r0 show the
device is held open by someone, I separately Executed echo "del 0"
>mgmt, and echo "del_target 117:1" > mgmt operation, but I still can't
turn down my drbd device. What do I need to do to release scst's
possession of drbd?

regards

Su Hua <suhua.tanke@gmail.com> 于2019年1月25日周五 下午12:41写道：

**Comment by bvanassche** [comment]
Are you using the vdisk_blockio handler? If so, how about writing "0" into the "active" attribute? From the SCST README:

> vdisk_blockio devices have the following two additional attributes:
> 
> - active - if this flag is set (the default), the backing block device
>   will be opened when the SCST device is added/opened. If a SCST device
>   is opened with active=0 then the backing block device will not be
>   opened, allowing for an active/passive SCST configuration. In addition,
>   this attribute is writable via sysfs allowing the user to open/close the
>   backing block device on the fly, or via a script.
