### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by sgermain06** [bvanassche/scst#2]
Hi, I'm getting this error on make all:

cc -c -o common.o -O2 -Wall -Wextra -Wno-unused-parameter -Wstrict-prototypes -I/usr/local/src/scst/usr/fileio/../../scst/include -I../include -D_GNU_SOURCE -D__USE_FILE_OFFSET64 -D__USE_LARGEFILE64 -DEXTRACHECKS -DDEBUG -g -fno-inline -fno-inline-functions -W -Wno-unused-parameter  -DDEBUG_EXT_COPY_REMAP common.c
common.c: In function ‘do_exec’:
common.c:440:14: error: ‘SERVICE_ACTION_IN_16’ undeclared (first use in this function)
         case SERVICE_ACTION_IN_16:
              ^
common.c:440:14: note: each undeclared identifier is reported only once for each function it appears in
Makefile:71: recipe for target 'common.o' failed
make[2]: *** [common.o] Error 1
make[2]: Leaving directory '/usr/local/src/scst/usr/fileio'

Help!

**Comment by bvanassche** [comment]
That's unexpected. With which Linux distro and which kernel version did this occur ? Can you also check whether there is perhaps an old version of scst_const.h present in /usr/local/include ?

**Comment by sgermain06** [comment]
I’m running Ubuntu 15.10 and the 4.2.3 kernel.

Let me check on the /usr/local/include...

**Comment by sgermain06** [comment]
Okay, there is a version in /usr/local/include, but I see the constant being defined there too.

# grep -rHin "SERVICE_ACTION_IN_16" *
scst_const.h:471: * See also patch "scsi: rename SERVICE_ACTION_IN_16 to SERVICE_ACTION_IN_16"
scst_const.h:474:#ifndef SERVICE_ACTION_IN_16
scst_const.h:475:#define SERVICE_ACTION_IN_16  0x9e

**Comment by bvanassche** [comment]
Removing the #if LINUX_VERSION_CODE < KERNEL_VERSION(3, 19, 0) / #endif pair from around the SERVICE_ACTION_IN_16 definition in scst_const.h should be sufficient to fix this build error. I will check in this change as a patch soon.

**Comment by sgermain06** [comment]
That did it! Thank you very much!
