### ISSUE TITLE
scst can not  run in linux docker when we start the process iscsi-scstd , error messaging: Connection refused for msgsend

### ISSUE THREAD

**Issue by tenderbulk** [bvanassche/scst#24]
Dear Mr Bart Van Assche , 
it would be so grateful for me if you could read out my message about a  scst error in linux docker env .  I am handling an issue that scst can not run in linux docker. I checked the iscsi-scstd calling trace symbols and found syscall sendmsg pops out an error : Connection refused as the below shown: 
socket(AF_NETLINK, SOCK_RAW, 0x19 /* NETLINK_??? */) = 7
getpid()                                = 25422
sendmsg(7, {msg_name(12)={sa_family=AF_NETLINK, pid=0, groups=00000000}, msg_iov(2)=[{"\20\0\0\0\0\0\0\0\0\0\0\0Nc\0\0", 16}, {NULL, 0}], msg_controllen=0, msg_flags=0}, 0) = -1 ECONNREFUSED (Connection refused)
fstat(1, {st_mode=S_IFCHR|0600, st_rdev=makedev(136, 1), ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fce020a8000
write(1, "nl_open -1\n", 11nl_open -1
)            = 11
close(7)  

These weeks, I googled  some solutions or similar issues and they all point to one : Docker NameSpace.  Actually, I can workround it by setting docker create --net=host to use the host net namepsace and unforunately this workaround has bad impact on the docker network system. 
so I am wondering if we have a plan to add the name space feature in iscsi-scst/kernel event.c 

thank you in advance 
the best regard！
 Chris  
DellEMC

**Comment by tenderbulk** [comment]
Adding OS information :
CentOS7.6
kernel 3.10.0-957-x86-64

**Comment by bvanassche** [comment]
Does the (untested) code on the network-namespace-support branch work better? See also https://github.com/bvanassche/scst/tree/network-namespace-support.

**Comment by tenderbulk** [comment]
Dear Mr Bart Van Assche ,
I am so appreciated for the patch you provided us with . Now I can have a break . My HOST sw manifiest ：
**CentOS 7.6 
Linux kernel 3.10.0-957 -x86-64
docker version : 1.13.1, build 64e9980/1.13.1
SCST Version : 3.5.0  cloned from github on 2020-04-20**

Besides, I also  checked it upon **UBUNTU18-04** with this patch . it seems to me that docker is pleasant with us . 

thank you so much 
Solute！！

--Chris

**Comment by tenderbulk** [comment]
I would like to close this issue
