### ISSUE TITLE
naa_id doesn't persist

### ISSUE THREAD

**Issue by dodexahedron** [bvanassche/scst#30]
Consider a device configured like this, in scst.conf:

        DEVICE lun1 {
                eui64_id 0x0000000300000001
                filename /path/to/file.lun
                t10_dev_id 00030001
                zero_copy 1
                naa_id 0x0000000300000001
        }

If I issue a `scstadmin -config /etc/scst.conf` and then `cat /sys/kernel/scst_tgt/devices/lun1/naa_id` the result is an empty string.

Also, if I issue a `scstadmin -write_config /etc/scst.conf`, the naa_id attribute is missing.

This behavior seems unexpected, from the documentation.

I also cannot echo a value into the naa_id 'file' in sys, or it gives `invalid argument`, whether I give it an 8 or 16-byte value.

Am I missing something or doing something wrong?

This is on code from current master as of this post.

**Comment by dodexahedron** [comment]
eui64_id has always worked, for me, so I kind of ignored this problem for the last year or so, but I thought I'd mention it.

**Comment by bvanassche** [comment]
SCST only accepts valid naa_id values. SCST verifies naa_id's as follows:
~~~
	switch (naa_id_len) {
	case 0:
	case 2 * 8:
		if (strchr("235", buf[0]))
			break;
		else
			goto out;
	case 2 * 16:
		if (strchr("6", buf[0]))
			break;
		else
			goto out;
	default:
		goto out;
	}
~~~
In other words, 8 byte naa_id's must start with one of the following digits: 2, 3 or 5. 16 byte naa_id's must start with the digit 6. A leading "0x" prefix is allowed.

**Comment by dodexahedron** [comment]
Good to know.
Thanks.
Closing.
