### ISSUE TITLE
copy_manager does not keep lun assignments on scstadmin -write_config

### ISSUE THREAD

**Issue by dodexahedron** [bvanassche/scst#31]
As the title says.

If I have copy_manager configured as:

    TARGET_DRIVER copy_manager {
            TARGET copy_manager_tgt {
                    LUN 0 disk_null
                    LUN 1 lun1
                    LUN 2 lun2
                    LUN 3 lun3
                    LUN 4 lun4
                    LUN 5 lun5
                    LUN 6 lun6
            }
    }

And then I issue a `scstadmin -write_config /etc/scst.conf` I end up with something like this:

    TARGET_DRIVER copy_manager {
            TARGET copy_manager_tgt {
                    LUN 0 lun1
                    LUN 1 disk_null
                    LUN 2 lun3
                    LUN 3 lun4
                    LUN 4 lun5
                    LUN 5 lun6
                    LUN 6 lun2
            }
    }

And it seems to be non-deterministic.

Does this affect the operation of it?
If not, I guess this is a non-issue.
But, at minimum, it seems like undesirable behavior for explicit configuration to change without good reason.

I have not observed this happening for anything other than copy_manager. For example, a group configured inside an iscsi target still keeps the correct mapping after a -write_config.

**Comment by bvanassche** [comment]
I think that scstadmin ignores the "copy_manager" section when it restores an scst.conf file and also that SCST assigns LUN numbers to devices in the order these devices are restored. In other words, it is expected that the LUN numbers for the copy manager do not match those from scst.conf.

**Comment by dodexahedron** [comment]
Thanks for clarifying.
Closing
