### ISSUE TITLE
missing kernel modules in debuginfo RPM

### ISSUE THREAD

**Issue by bprotopopov** [bvanassche/scst#4]
Executable bit is not set on the kernel modules resulting in them not being included in the debuginfo RPM.

**Comment by bvanassche** [comment]
Hmm ... it's not clear to me why you want the kernel modules to be present in both the SCST RPM itself and in the debuginfo RPM? I think it's sufficient if the /usr/lib/debug and /usr/src/debug files are present in the debug RPM.

**Comment by bprotopopov** [comment]
@bvanassche, I am looking to include the .debug counterparts of the kernel module object files, not the object files themselves, i.e.

```
/usr/lib/debug/lib/modules/2.6.32-573.12.1.el6.x86_64/extra/dev_handlers/scst_cdrom.ko.debug
/usr/lib/debug/lib/modules/2.6.32-573.12.1.el6.x86_64/extra/dev_handlers/scst_changer.ko.debug
/usr/lib/debug/lib/modules/2.6.32-573.12.1.el6.x86_64/extra/dev_handlers/scst_disk.ko.debug
/usr/lib/debug/lib/modules/2.6.32-573.12.1.el6.x86_64/extra/dev_handlers/scst_modisk.ko.debug
/usr/lib/debug/lib/modules/2.6.32-573.12.1.el6.x86_64/extra/dev_handlers/scst_processor.ko.debug
/usr/lib/debug/lib/modules/2.6.32-573.12.1.el6.x86_64/extra/dev_handlers/scst_raid.ko.debug
/usr/lib/debug/lib/modules/2.6.32-573.12.1.el6.x86_64/extra/dev_handlers/scst_tape.ko.debug
/usr/lib/debug/lib/modules/2.6.32-573.12.1.el6.x86_64/extra/dev_handlers/scst_user.ko.debug
/usr/lib/debug/lib/modules/2.6.32-573.12.1.el6.x86_64/extra/dev_handlers/scst_vdisk.ko.debug
/usr/lib/debug/lib/modules/2.6.32-573.12.1.el6.x86_64/extra/iscsi-scst.ko.debug
/usr/lib/debug/lib/modules/2.6.32-573.12.1.el6.x86_64/extra/scst.ko.debug
/usr/lib/debug/lib/modules/2.6.32-573.12.1.el6.x86_64/extra/scst_local.ko.debug
```

These are produced by /usr/lib/rpm/find-debuginfo.sh in the process of building debug RPMs, but the latter only considers files with executable bit set.

**Comment by bvanassche** [comment]
I'd like to reproduce this myself before I start working on a fix. Which Linux distribution are you using and which version of that distribution?

**Comment by bprotopopov** [comment]
I am using centos 6.7. But I am fairly certain this is not a distro-specific problem.

**Comment by bvanassche** [comment]
This is weird. As far as I know the kernel module build process on CentOS does not generate separate .ko.debug files. Have you perhaps modified the SCST RPM generation process and/or the CentOS module build process to separate the .ko.debug files from the .ko files? From a CentOS system after having built and installed SCST:

[root@centos6-vm ~]# uname -a
Linux centos6-vm 2.6.32-573.22.1.el6.x86_64 #1 SMP Wed Mar 23 03:35:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[root@centos6-vm ~]# find / -xdev | wc -l
92302
[root@centos6-vm ~]# find / -xdev -name '*.ko.debug' | wc -l
0

**Comment by bprotopopov** [comment]
No. Not really.

Why not try building SCST "for release", then install the RPMs (including debuginfo), load your module, crash the kernel, and use crash to on the core dump to see if you can find any SCST symbols ? Then try setting the executable bits as I suggest, repeating the above process, and observe the difference.
 
I think this would be the "unit test" to eliminate any uncertainty.

Another option is to take a look at other projects on github, e.g. SPL/ZFS, to see how they deal with this issue.

**Comment by bprotopopov** [comment]
Oh, yes. Here is probably the simplest answer to your question:
```
[build@centos-6 curl]$ rpm -ql kernel-debuginfo | egrep 'ko.debug' 
...
/usr/lib/debug/lib/modules/2.6.32-573.12.1.el6.x86_64/kernel/sound/usb/6fire/snd-usb-6fire.ko.debug
/usr/lib/debug/lib/modules/2.6.32-573.12.1.el6.x86_64/kernel/sound/usb/bcd2000/snd-bcd2000.ko.debug
/usr/lib/debug/lib/modules/2.6.32-573.12.1.el6.x86_64/kernel/sound/usb/caiaq/snd-usb-caiaq.ko.debug
/usr/lib/debug/lib/modules/2.6.32-573.12.1.el6.x86_64/kernel/sound/usb/hiface/snd-usb-hiface.ko.debug
/usr/lib/debug/lib/modules/2.6.32-573.12.1.el6.x86_64/kernel/sound/usb/misc/snd-ua101.ko.debug
/usr/lib/debug/lib/modules/2.6.32-573.12.1.el6.x86_64/kernel/sound/usb/snd-usb-audio.ko.debug
/usr/lib/debug/lib/modules/2.6.32-573.12.1.el6.x86_64/kernel/sound/usb/snd-usbmidi-lib.ko.debug
/usr/lib/debug/lib/modules/2.6.32-573.12.1.el6.x86_64/kernel/sound/usb/usx2y/snd-usb-us122l.ko.debug
/usr/lib/debug/lib/modules/2.6.32-573.12.1.el6.x86_64/kernel/sound/usb/usx2y/snd-usb-usx2y.ko.debug
[build@centos-6 curl]$ rpm -ql kernel-debuginfo | egrep 'ko.debug' | wc -l
2033
```
You probably do not have the debuginfo RPM installed on your system ?

**Comment by bvanassche** [comment]
As far as I can see CentOS provides a kernel-debug RPM but no kernel-debuginfo RPM:

    # yum search kernel-debuginfo
    # yum search kernel-debug
    ========================== N/S Matched: kernel-debug ===========================
    kernel-debug.x86_64 : The Linux kernel compiled with extra debugging enabled
    kernel-debug-devel.i686 : Development package for building kernel modules to
                            : match the debug kernel
    kernel-debug-devel.x86_64 : Development package for building kernel modules to
                              : match the debug kernel

**Comment by bprotopopov** [comment]
I am afraid I do not follow. 

Would you like me to help you setup your system such that you can find and install the kernel-debuginfo 
e.g. from http://debuginfo.centos.org/6/x86_64/kernel-debuginfo-2.6.32-573.12.1.el6.x86_64.rpm ?

**Comment by bvanassche** [comment]
Sorry - I forgot to enable the debug repo (CentOS-Debuginfo.repo). Can you test the following patch:

    scst.spec.in: Make sure that find-debuginfo.sh can find the SCST kernel modules

    diff --git a/scst.spec.in b/scst.spec.in
    index e7138ce..bc8900f 100644
    --- a/scst.spec.in
    +++ b/scst.spec.in
    @@ -140,6 +140,9 @@ for d in qla2x00t_git/qla2x00-target qla2x00t/qla2x00-target
            break
         fi
     done
    +# Set executable bit such that /usr/lib/rpm/find-debuginfo.sh finds the
    +# SCST kernel modules.
    +find %{buildroot}/lib/modules -name '*.ko' -print0 | xargs -0 chmod u+x
     rm -f %{buildroot}/lib/modules/%{kversion}/[Mm]odule*
     
     %clean

**Comment by bprotopopov** [comment]
@bvanassche, sorry for the delayed reply. 
I think you your change should work, but my preference is to fix the root cause in the Makefiles (here is a patch from my repo):

```
...
diff --git a/iscsi-scst/Makefile b/iscsi-scst/Makefile
index 405a63c..36364cf 100644
--- a/iscsi-scst/Makefile
+++ b/iscsi-scst/Makefile
@@ -72,6 +72,7 @@ install: all
        $(MAKE) -C $(KDIR) SCST_INC_DIR=$(SCST_INC_DIR) SUBDIRS=$(KMOD) \
          $$([ -n "$(DESTDIR)$(INSTALL_MOD_PATH)" ] && echo DEPMOD=true) \
          modules_install
+       chmod u+x $(INSTALL_DIR)/*.ko
 
 uninstall:
        rm -f $(DESTDIR)$(SBINDIR)/iscsi-scstd \
diff --git a/scst/src/Makefile b/scst/src/Makefile
index 6fa3ed6..936faa0 100644
--- a/scst/src/Makefile
+++ b/scst/src/Makefile
@@ -92,8 +92,8 @@ install: all
        -rm -f $(INSTALL_DIR)/scsi_tgt.ko
        install -d $(INSTALL_DIR)
        install -d $(INSTALL_DIR)/dev_handlers
-       install -m 644 dev_handlers/*.ko $(INSTALL_DIR)/dev_handlers
-       install -m 644 scst.ko $(INSTALL_DIR)
+       install -m 744 dev_handlers/*.ko $(INSTALL_DIR)/dev_handlers
+       install -m 744 scst.ko $(INSTALL_DIR)
        install -d $(INSTALL_DIR_H)
        install -m 644 ../include/scst.h $(INSTALL_DIR_H)
        install -m 644 ../include/scst_sgv.h $(INSTALL_DIR_H)
diff --git a/scst/src/dev_handlers/Makefile b/scst/src/dev_handlers/Makefile
index f3f8b96..13c96a6 100644
--- a/scst/src/dev_handlers/Makefile
+++ b/scst/src/dev_handlers/Makefile
@@ -75,6 +75,7 @@ install: all
        $(MAKE) -C $(KDIR) SUBDIRS=$(shell pwd) \
                $$([ -n "$(DESTDIR)$(INSTALL_MOD_PATH)" ] && echo DEPMOD=true) \
                modules_install
+       chmod u+x $(INSTALL_DIR)/dev_handlers/scst_*.ko
 
 uninstall:
        rm -f $(INSTALL_DIR)/dev_handlers/scst_*.ko
diff --git a/scst_local/Makefile b/scst_local/Makefile
index 7eba6e4..69d74ee 100644
--- a/scst_local/Makefile
+++ b/scst_local/Makefile
@@ -63,6 +63,7 @@ install: all
        $(MAKE) -C $(KDIR) SUBDIRS=$(shell pwd) BUILD_INI=m \
                $$([ -n "$(DESTDIR)$(INSTALL_MOD_PATH)" ] && echo DEPMOD=true) \
                SCST_INC_DIR=$(SCST_INC_DIR) modules_install
+       chmod u+x $(INSTALL_DIR)/*.ko
 
 SCST_MOD_VERS := $(shell ls $(SCST_DIR)/Modules.symvers 2>/dev/null)
 ifneq ($(SCST_MOD_VERS),)
(END) 
```

**Comment by bvanassche** [comment]
The above patch sets the execute bit for all kernel modules which is something I'd like to avoid. How about the patch below that enables generation of .ko.debug files but without leaving the execute bit enabled for .ko files:

    [PATCH] scst.spec.in: Enable .debug generation for .ko files (v2)

    diff --git a/scst.spec.in b/scst.spec.in
    index e7138ce..31df835 100644
    --- a/scst.spec.in
    +++ b/scst.spec.in
    @@ -140,6 +140,9 @@ for d in qla2x00t_git/qla2x00-target qla2x00t/qla2x00-target; do
     	break
         fi
     done
    +# Set the executable bit such that /usr/lib/rpm/find-debuginfo.sh can find the
    +# SCST kernel modules.
    +find %{buildroot}/lib/modules -name '*.ko' -print0 | xargs -0 chmod u+x
     rm -f %{buildroot}/lib/modules/%{kversion}/[Mm]odule*
     
     %clean
    @@ -160,7 +163,7 @@ rm -rf /usr/local/include/scst
     /sbin/depmod -a %{kversion}
     
     %files
    -%defattr(-,root,root)
    +%defattr(0644,root,root)
     %dir /lib/modules/%{kversion}/extra
     /lib/modules/%{kversion}/extra/fcst.ko
     /lib/modules/%{kversion}/extra/ib_srpt.ko
    @@ -180,6 +183,7 @@ rm -rf /usr/local/include/scst
     /lib/modules/%{kversion}/extra/dev_handlers/scst_tape.ko
     /lib/modules/%{kversion}/extra/dev_handlers/scst_user.ko
     /lib/modules/%{kversion}/extra/dev_handlers/scst_vdisk.ko
    +%defattr(-,root,root)
     %{_mandir}/man5/iscsi-scstd.conf.5.gz
     %{_mandir}/man8/iscsi-scst-adm.8.gz
     %{_mandir}/man8/iscsi-scstd.8.gz

**Comment by bvanassche** [comment]
The above patch has been checked in on the svn-trunk and master branches.
