### ISSUE TITLE
How much can the client end read and write performance reach?

### ISSUE THREAD

**Issue by mashiguo** [bvanassche/scst#40]
I want to know if anyone has tested the I/O performance of the client's disk after it is suspended.
What I am doing now is that the client discovers the target, logs in and mounts the corresponding disk (240GSSD solid state disk), passes through the gigabit switch, and uses the fio tool to read and write tests (fio -filename=/oa/2G -direct=1 -iodepth= 1 -thread -rw=write -ioengine=psync -bs=4k -size=10G -numjobs=1 -runtime=200 -group_reporting -name=writetest), test block size 4M, and 4K, the result:
[Test Results .xlsx](https://github.com/bvanassche/scst/files/6747510/Test.Results.xlsx)
I want to know the approximate range of I/O!
Thank you very much if you inform!

**Comment by bvanassche** [comment]
The answer depends on how fast the local storage is, how fast the network is and also on whether or not there are any bottlenecks in the initiator system. For more information, see also https://github.com/bvanassche/scst/blob/master/README.performance.

**Comment by mashiguo** [comment]
@bvanassche thank you very much !
