### ISSUE TITLE
The service always stops automatically 

### ISSUE THREAD

**Issue by mashiguo** [bvanassche/scst#41]
The problem I have now is that after modifying the configuration file /etc/scst.conf and executing /etc/init.d/scst restart, the service can run normally but the service stops after a while. The system log is as follows: 

 9 14:10:31 localhost kernel: [10629]: iscsi-scst: Releasing allocated resources
Jul  9 14:10:31 localhost kernel: [10629]: iscsi-scst: iser portal cm_id:ffff88045f0d9800 releasing
Jul  9 14:10:31 localhost kernel: [10629]: iscsi-scst: done releasing portal ffff88045f898bc0
Jul  9 14:10:31 localhost kernel: [10629]: scst: Target iqn.2016-07:net.hg:1 for template iscsi unregistered successfully
Jul  9 14:10:31 localhost nmbd[28687]: [2021/07/09 14:10:31.913841,  0] ../source3/nmbd/nmbd.c:58(terminate)
Jul  9 14:10:31 localhost nmbd[28687]:   Got SIGTERM: going down...
Jul  9 14:10:32 localhost cmdserver_deamon[6432]: Socket Exception : An unknown error occured (errno = 0x00000068)
Jul  9 14:10:32 localhost kernel: [29173]: iscsi-scst: Unregistered iSCSI transport: iSER
Jul  9 14:10:32 localhost kernel: [29188]: qla2x00t: Unloading QLogic Fibre Channel HBA Driver target mode addon driver
Jul  9 14:10:32 localhost kernel: [29188]: scst: Target template qla2x00t unregistered successfully
Jul  9 14:10:32 localhost kernel: [10498]: iscsi-scst: Read thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10499]: iscsi-scst: Read thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10500]: iscsi-scst: Read thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10501]: iscsi-scst: Read thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10502]: iscsi-scst: Read thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10503]: iscsi-scst: Read thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10504]: iscsi-scst: Read thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10505]: iscsi-scst: Read thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10506]: iscsi-scst: Read thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10507]: iscsi-scst: Read thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10508]: iscsi-scst: Read thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10509]: iscsi-scst: Read thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10510]: iscsi-scst: Read thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10511]: iscsi-scst: Read thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10512]: iscsi-scst: Read thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10513]: iscsi-scst: Read thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10514]: iscsi-scst: Read thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10515]: iscsi-scst: Read thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10516]: iscsi-scst: Read thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10517]: iscsi-scst: Read thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10518]: iscsi-scst: Read thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10519]: iscsi-scst: Read thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10520]: iscsi-scst: Read thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10521]: iscsi-scst: Read thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10522]: iscsi-scst: Read thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10523]: iscsi-scst: Read thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10524]: iscsi-scst: Read thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10525]: iscsi-scst: Read thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10526]: iscsi-scst: Read thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10527]: iscsi-scst: Read thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10528]: iscsi-scst: Read thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10529]: iscsi-scst: Read thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10530]: iscsi-scst: Write thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10531]: iscsi-scst: Write thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10532]: iscsi-scst: Write thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10533]: iscsi-scst: Write thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10534]: iscsi-scst: Write thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10535]: iscsi-scst: Write thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10536]: iscsi-scst: Write thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10537]: iscsi-scst: Write thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10538]: iscsi-scst: Write thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10539]: iscsi-scst: Write thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10540]: iscsi-scst: Write thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10541]: iscsi-scst: Write thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10542]: iscsi-scst: Write thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10543]: iscsi-scst: Write thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10544]: iscsi-scst: Write thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10545]: iscsi-scst: Write thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10546]: iscsi-scst: Write thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10547]: iscsi-scst: Write thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10548]: iscsi-scst: Write thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10549]: iscsi-scst: Write thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10550]: iscsi-scst: Write thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10551]: iscsi-scst: Write thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10552]: iscsi-scst: Write thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10553]: iscsi-scst: Write thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10554]: iscsi-scst: Write thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10555]: iscsi-scst: Write thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10556]: iscsi-scst: Write thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10557]: iscsi-scst: Write thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10558]: iscsi-scst: Write thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10559]: iscsi-scst: Write thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10560]: iscsi-scst: Write thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [10561]: iscsi-scst: Write thread for pool ffff880460693c00 finished
Jul  9 14:10:32 localhost kernel: [29191]: scst: Target template iscsi unregistered successfully
Jul  9 14:10:32 localhost kernel: [29191]: iscsi-scst: Unregistered iSCSI transport: iSCSI-TCP
Jul  9 14:10:32 localhost kernel: [29194]: scst: Removed LUN 0 from group copy_manager_tgt (target copy_manager_tgt)
Jul  9 14:10:32 localhost kernel: [29194]: dev_vdisk: Detached virtual device disk01 ("/dev/sda")
Jul  9 14:10:32 localhost kernel: [29194]: scst: Detached from virtual device disk01 (id 1)
Jul  9 14:10:32 localhost kernel: [29194]: dev_vdisk: Virtual device disk01 unregistered
Jul  9 14:10:32 localhost kernel: [29194]: scst: Removed LUN 1 from group copy_manager_tgt (target copy_manager_tgt)
Jul  9 14:10:32 localhost kernel: [29194]: dev_vdisk: Detached virtual device dummy ("/dev/ram0")
Jul  9 14:10:32 localhost kernel: [29194]: scst: Detached from virtual device dummy (id 2)
Jul  9 14:10:32 localhost kernel: [29194]: dev_vdisk: Virtual device dummy unregistered
Jul  9 14:10:32 localhost kernel: [29194]: scst: Removed LUN 2 from group copy_manager_tgt (target copy_manager_tgt)
Jul  9 14:10:32 localhost kernel: [29194]: dev_vdisk: Detached virtual device oa ("/dev/ram0")
Jul  9 14:10:32 localhost kernel: [29194]: scst: Detached from virtual device oa (id 3)
Jul  9 14:10:32 localhost kernel: [29194]: dev_vdisk: Virtual device oa unregistered
Jul  9 14:10:32 localhost kernel: [29194]: scst: Device handler "vdisk_nullio" unloaded
Jul  9 14:10:32 localhost kernel: [29194]: scst: Device handler "vdisk_blockio" unloaded
Jul  9 14:10:32 localhost kernel: [29194]: scst: Device handler "vdisk_fileio" unloaded
Jul  9 14:10:32 localhost kernel: [29194]: scst: Device handler "vcdrom" unloaded
Jul  9 14:10:32 localhost kernel: [29199]: scst: Target copy_manager_tgt for template copy_manager unregistered successfully
Jul  9 14:10:32 localhost kernel: [29199]: scst: Target template copy_manager unregistered successfully
Jul  9 14:10:32 localhost kernel: [10494]: scst: Task management thread finished
Jul  9 14:10:32 localhost kernel: [10495]: scst: Management thread finished
Jul  9 14:10:32 localhost kernel: [10493]: scst: Init thread finished
Jul  9 14:10:32 localhost kernel: [29199]: scst: Detached from scsi0, channel 2, id 0, lun 0, type 0
Jul  9 14:10:32 localhost kernel: [29199]: scst: Detached from scsi1, channel 0, id 0, lun 0, type 0
Jul  9 14:10:32 localhost kernel: [29199]: scst: Detached from scsi5, channel 0, id 0, lun 0, type 0
Jul  9 14:10:32 localhost kernel: [29199]: scst: Exiting SCST sysfs hierarchy...
Jul  9 14:10:33 localhost cmdserver_deamon[6432]: Socket Exception : An unknown error occured (errno = 0x00000068)
Jul  9 14:10:34 localhost cmdserver_deamon[6432]: Socket Exception : An unknown error occured (errno = 0x00000068)
Jul  9 14:10:35 localhost kernel: [10371]: scst: User interface thread finished
Jul  9 14:10:35 localhost kernel: [29199]: scst: Exiting SCST sysfs hierarchy done
Jul  9 14:10:35 localhost kernel: [29199]: scst: SCST unloaded

**Comment by bvanassche** [comment]
I haven't seen this before. Which Linux distribution are you using and which version? Is SCST  being started inside a container or not?

**Comment by mashiguo** [comment]
@bvanassche Thank you! The linux kernel version 2.6.32-696.el6.x86_64, scst-3.3.0, does not run in the container, it is no problem now, but I did not find the specific reason, it may be caused by my other services, I am actually a cluster I used the above, I started corosync and pacemaker, and then started scst and it was OK

**Comment by bvanassche** [comment]
Please check the Pacemaker configuration. SCST does not stop by itself - it only stops if told to stop by running `/etc/init.d/scst stop`.

**Comment by bvanassche** [comment]
Please reopen this report if this issue has not yet been resolved.
