### ISSUE TITLE
Use scst version 3.5 with kernel centos 4.14.44 call soft lockup!

### ISSUE THREAD

**Issue by oracleloyall** [bvanassche/scst#42]
With scst 3.5 version and linux kernel with centos(4.14.44 x86) ! The system log is as follows!
Jul 12 05:00:18 cdm-storage kernel: [18574]: iscsi-scst: Freeing conn ffffa0477b454440 (sess=ffffa03d47fae600, 0x97fb0100003d0200 0, initiator iqn.1994-05.com.redhat:221930adcc15)
Jul 12 05:00:18 cdm-storage kernel: [18574]: iscsi-scst: Freeing session ffffa03d47fae600 (SID 97fb0100003d0200)
Jul 12 05:00:18 cdm-storage kernel: [8032]: scst: Using security group "g-7bcce7ae" for initiator "iqn.1994-05.com.redhat:221930adcc15" (target iqn.2016-07.com.ecloudtech:cdm-storage.stor)
Jul 12 05:00:18 cdm-storage kernel: [8032]: iscsi-scst: Session ffffa0405d39b300 created: target ffffa04bb6de6600, tid 1, sid 0x97fd0100003d0200, initiator iqn.1994-05.com.redhat:221930adcc15
Jul 12 05:00:18 cdm-storage kernel: [8032]: iscsi-scst: Negotiated parameters: InitialR2T No, ImmediateData Yes, MaxConnections 1, MaxRecvDataSegmentLength 1048576, MaxXmitDataSegmentLength 262144, 
Jul 12 05:00:18 cdm-storage kernel: [8032]: iscsi-scst:     MaxBurstLength 1048576, FirstBurstLength 65536, DefaultTime2Wait 0, DefaultTime2Retain 0, 
Jul 12 05:00:18 cdm-storage kernel: [8032]: iscsi-scst:     MaxOutstandingR2T 1, DataPDUInOrder Yes, DataSequenceInOrder Yes, ErrorRecoveryLevel 0, 
Jul 12 05:00:18 cdm-storage kernel: [8032]: iscsi-scst:     HeaderDigest None, DataDigest None, OFMarker No, IFMarker No, OFMarkInt 2048, IFMarkInt 2048, RDMAExtensions No
Jul 12 05:00:18 cdm-storage kernel: [8032]: iscsi-scst: Target parameters set for session 97fd0100003d0200: QueuedCommands 32, Response timeout 90, Nop-In interval 30, Nop-In timeout 30
Jul 12 05:00:18 cdm-storage kernel: [8032]: iscsi-scst: Deleting session ffffa03d40d4b300 (initiator iqn.1994-05.com.redhat:221930adcc15)
Jul 12 05:00:18 cdm-storage kernel: [8032]: iscsi-scst: Creating connection ffffa046b57b2d80 for sid 0x97fd0100003d0200, cid 0 (initiator iqn.1994-05.com.redhat:221930adcc15)
Jul 12 05:00:18 cdm-storage kernel: [18578]: scst: TM fn NEXUS_LOSS_SESS/6 (mcmd ffffa04a201bcaf0, initiator iqn.1994-05.com.redhat:221930adcc15, target iqn.2016-07.com.ecloudtech:cdm-storage.stor)
Jul 12 05:00:18 cdm-storage kernel: [7823]: scst: TM fn 6 (mcmd ffffa04a201bcaf0) finished, status 0
Jul 12 05:00:18 cdm-storage kernel: [18578]: iscsi-scst: Freeing conn ffffa0447fb04440 (sess=ffffa03d40d4b300, 0x97fc0100003d0200 0, initiator iqn.1994-05.com.redhat:221930adcc15)
Jul 12 05:00:18 cdm-storage kernel: [18578]: iscsi-scst: Freeing session ffffa03d40d4b300 (SID 97fc0100003d0200)
Jul 12 05:00:18 cdm-storage kernel: [8032]: scst: Using security group "g-7bcce7ae" for initiator "iqn.1994-05.com.redhat:221930adcc15" (target iqn.2016-07.com.ecloudtech:cdm-storage.stor)
Jul 12 05:00:18 cdm-storage kernel: watchdog: BUG: soft lockup - CPU#51 stuck for 22s! [kworker/51:1:24566]
Jul 12 05:00:18 cdm-storage kernel: Modules linked in: iptable_raw xt_CHECKSUM iptable_mangle ipt_MASQUERADE nf_nat_masquerade_ipv4 iptable_nat nf_nat_ipv4 nf_nat nf_conntrack_ipv4 nf_defrag_ipv4 xt_conntrack nf_conntrack ipt_REJECT nf_reject_ipv4 tun bridge stp llc ebtable_filter ebtables ip6table_filter ip6_tables iptable_filter devlink qla2x00tgt(OE) scst_vdisk(OE) isert_scst(OE) iscsi_scst(OE) scst(OE) dlm libcrc32c rpcrdma bonding ib_iser libiscsi scsi_transport_iscsi ib_srp scsi_transport_srp ib_ipoib rdma_ucm ib_ucm ib_uverbs ib_umad rdma_cm ib_cm iw_cm intel_rapl zfs(POE) skx_edac zunicode(POE) x86_pkg_temp_thermal zlua(POE) vfat fat coretemp crct10dif_pclmul crc32_pclmul zcommon(POE) znvpair(POE) zavl(POE) ghash_clmulni_intel pcbc i40iw icp(POE) aesni_intel spl(OE) ses enclosure crypto_simd glue_helper scsi_transport_sas
Jul 12 05:00:18 cdm-storage kernel: iTCO_wdt qla2xxx_scst(OE) mei_me cryptd ib_core iTCO_vendor_support shannon(OE) sg scsi_transport_fc joydev mei pcspkr ioatdma shpchp i2c_i801 lpc_ich wmi ipmi_si ipmi_devintf ipmi_msghandler acpi_power_meter nfsd auth_rpcgss nfs_acl lockd sch_fq binfmt_misc grace sunrpc ip_tables sd_mod ast i2c_algo_bit drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops ttm drm ixgbe i40e ahci mdio libahci crc32c_intel megaraid_sas libata ptp dca i2c_core pps_core dm_mirror dm_region_hash dm_log dm_mod
Jul 12 05:00:18 cdm-storage kernel: CPU: 51 PID: 24566 Comm: kworker/51:1 Tainted: P        W  OEL  4.14.44 #1
Jul 12 05:00:18 cdm-storage kernel: Hardware name: eCloudTech eCloudTech/Curry, BIOS 4.1.8 06/20/2019
Jul 12 05:00:18 cdm-storage kernel: Workqueue: events_power_efficient fb_flashcursor
Jul 12 05:00:18 cdm-storage kernel: task: ffffa047ddec5a00 task.stack: ffffc0580c95c000
Jul 12 05:00:18 cdm-storage kernel: RIP: 0010:console_unlock+0x24e/0x4d0
Jul 12 05:00:18 cdm-storage kernel: RSP: 0018:ffffc0580c95fe38 EFLAGS: 00000246 ORIG_RAX: ffffffffffffff10
Jul 12 05:00:18 cdm-storage kernel: RAX: 0000000000000000 RBX: 00000000000000b1 RCX: 00000000ffffffff
Jul 12 05:00:18 cdm-storage kernel: RDX: ffffc0580c95fde8 RSI: 0000000000000004 RDI: 0000000000000246
Jul 12 05:00:18 cdm-storage kernel: RBP: 0000000000000400 R08: 0000000000000000 R09: 0000000000000001
Jul 12 05:00:18 cdm-storage kernel: R10: 00000000000003ff R11: 0000000000aaaaaa R12: 0000000000000246
Jul 12 05:00:18 cdm-storage kernel: R13: 0000000000000000 R14: 00000000000000b1 R15: 0000000000000000
Jul 12 05:00:18 cdm-storage kernel: FS:  0000000000000000(0000) GS:ffffa04bbf6c0000(0000) knlGS:0000000000000000
Jul 12 05:00:18 cdm-storage kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Jul 12 05:00:18 cdm-storage kernel: CR2: 00007f8279c81000 CR3: 0000003921e0a003 CR4: 00000000007606e0
Jul 12 05:00:18 cdm-storage kernel: DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
Jul 12 05:00:18 cdm-storage kernel: DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
Jul 12 05:00:18 cdm-storage kernel: PKRU: 55555554
Jul 12 05:00:18 cdm-storage kernel: Call Trace:
Jul 12 05:00:18 cdm-storage kernel: process_one_work+0x155/0x370
Jul 12 05:00:18 cdm-storage kernel: worker_thread+0x47/0x3e0
Jul 12 05:00:18 cdm-storage kernel: kthread+0xff/0x140
Jul 12 05:00:18 cdm-storage kernel: ? max_active_store+0x80/0x80
Jul 12 05:00:18 cdm-storage kernel: ? __kthread_parkme+0x70/0x70
Jul 12 05:00:18 cdm-storage kernel: ret_from_fork+0x35/0x40
Jul 12 05:00:18 cdm-storage kernel: Code: 0f 84 b3 01 00 00 4c 89 ef 44 89 fa 48 c7 c6 80 d3 61 8a e8 45 3a b2 00 4d 8b 6d 50 4d 85 ed 75 a3 e8 37 17 00 00 4c 89 e7 57 9d <0f> 1f 44 00 00 8b 54 24 0c 85 d2 0f 84 23 fe ff ff e8 0c 07 73 
Jul 12 05:00:18 cdm-storage kernel: [8032]: iscsi-scst: Session ffffa0448bbd3300 created: target ffffa04bb6de6600, tid 1, sid 0x97fe0100003d0200, initiator iqn.1994-05.com.redhat:221930adcc15
Jul 12 05:00:18 cdm-storage kernel: [8032]: iscsi-scst: Negotiated parameters: InitialR2T No, ImmediateData Yes, MaxConnections 1, MaxRecvDataSegmentLength 1048576, MaxXmitDataSegmentLength 262144, 
Jul 12 05:00:18 cdm-storage kernel: [8032]: iscsi-scst:     MaxBurstLength 1048576, FirstBurstLength 65536, DefaultTime2Wait 0, DefaultTime2Retain 0, 
Jul 12 05:00:18 cdm-storage kernel: [8032]: iscsi-scst:     MaxOutstandingR2T 1, DataPDUInOrder Yes, DataSequenceInOrder Yes, ErrorRecoveryLevel 0, 
Jul 12 05:00:18 cdm-storage kernel: [8032]: iscsi-scst:     HeaderDigest None, DataDigest None, OFMarker No, IFMarker No, OFMarkInt 2048, IFMarkInt 2048, RDMAExtensions No
Jul 12 05:00:18 cdm-storage kernel: [8032]: iscsi-scst: Target parameters set for session 97fe0100003d0200: QueuedCommands 32, Response timeout 90, Nop-In interval 30, Nop-In timeout 30
Jul 12 05:00:18 cdm-storage kernel: [8032]: iscsi-scst: Deleting session ffffa0405d39b300 (initiator iqn.1994-05.com.redhat:221930adcc15)
Jul 12 05:00:18 cdm-storage kernel: [8032]: iscsi-scst: Creating connection ffffa04441b4f840 for sid 0x97fe0100003d0200, cid 0 (initiator iqn.1994-05.com.redhat:221930adcc15)
Jul 12 05:00:18 cdm-storage kernel: [18582]: scst: TM fn NEXUS_LOSS_SESS/6 (mcmd ffffa04724b55f50, initiator iqn.1994-05.com.redhat:221930adcc15, target iqn.2016-07.com.ecloudtech:cdm-storage.stor)
Jul 12 05:00:18 cdm-storage kernel: [7823]: scst: TM fn 6 (mcmd ffffa04724b55f50) finished, status 0
Jul 12 05:00:18 cdm-storage kernel: [18582]: iscsi-scst: Freeing conn ffffa046b57b2d80 (sess=ffffa0405d39b300, 0x97fd0100003d0200 0, initiator iqn.1994-05.com.redhat:221930adcc15)
Jul 12 05:00:18 cdm-storage kernel: [18582]: iscsi-scst: Freeing session ffffa0405d39b300 (SID 97fd0100003d0200)

**Comment by bvanassche** [comment]
Are you using the 3.5.x branch? If so, which version? A fix for a soft lockup got checked in on June 23. See also commit be9d1fa2a222e640a50f838c13accb30aadccb90.

**Comment by bvanassche** [comment]
Please reopen if this needs further attention.
