### ISSUE TITLE
Kernel 5.13.4 throws BPF: Invalid Name when trying to load scst Modules

### ISSUE THREAD

**Issue by ASTuser1** [bvanassche/scst#43]
Hi ,

first of all - i am regulary not at all very much into solving such complex errors.

Compiling SCST with Ubuntu 21.04 (X64), a fresh compiled Kernel 5.13.4 and loading the generated modules leds to the following error 

>root@xxx/home/bla/scst# for m in scst qla2xxx_scst qla2x00tgt scst_vdisk scst_user scst_disk ; do modprobe $m; done
>dmesgmodprobe: ERROR: could not insert 'scst': Invalid argument
>modprobe: ERROR: could not insert 'qla2xxx_scst': Invalid argument
>modprobe: ERROR: could not insert 'qla2x00tgt': Invalid argument
>modprobe: ERROR: could not insert 'scst_vdisk': Invalid argument
>modprobe: ERROR: could not insert 'scst_user': Invalid argument
>modprobe: ERROR: could not insert 'scst_disk': Invalid argument

`
[ 3336.440260] failed to validate module [scst] BTF: -22
[ 3496.545174] BPF:[120294] ENUM ps_convert_ctx_access 
[ 3496.545178] BPF:size=4 vlen=4
[ 3496.545179] BPF: 
[ 3496.545180] BPF:Invalid name
[ 3496.545181] BPF:

[ 3496.545183] failed to validate module [scst] BTF: -22
[ 3496.675437] BPF:[120301] ENUM ess 
[ 3496.675442] BPF:size=4 vlen=12
[ 3496.675443] BPF: 
[ 3496.675444] BPF:Invalid name
[ 3496.675445] BPF:

[ 3496.675447] failed to validate module [qla2xxx_scst] BTF: -22
[ 3496.819806] BPF:[120301] ENUM ess 
[ 3496.819811] BPF:size=4 vlen=12
[ 3496.819812] BPF: 
[ 3496.819812] BPF:Invalid name
[ 3496.819813] BPF:

[ 3496.819815] failed to validate module [qla2xxx_scst] BTF: -22
[ 3496.915932] BPF:[120294] ENUM ps_convert_ctx_access 
[ 3496.915936] BPF:size=4 vlen=4
[ 3496.915937] BPF: 
[ 3496.915938] BPF:Invalid name
[ 3496.915939] BPF:

[ 3496.915941] failed to validate module [scst] BTF: -22
[ 3497.027934] BPF:[120294] ENUM ps_convert_ctx_access 
[ 3497.027940] BPF:size=4 vlen=4
[ 3497.027941] BPF: 
[ 3497.027942] BPF:Invalid name
[ 3497.027942] BPF:

[ 3497.027945] failed to validate module [scst] BTF: -22
[ 3497.135914] BPF:[120294] ENUM ps_convert_ctx_access 
[ 3497.135919] BPF:size=4 vlen=4
[ 3497.135920] BPF: 
[ 3497.135921] BPF:Invalid name
[ 3497.135922] BPF:

[ 3497.135924] failed to validate module [scst] BTF: -22
`
modinfo:

root@bla-OptiPlex-3020:/home/bla/scst# modinfo scst
filename:       /lib/modules/5.13.4-051304-generic/extra/scst.ko
version:        3.6.0-pre
description:    SCSI target core
license:        GPL
author:         Vladislav Bolkhovitin
srcversion:     2480D6A307C798668D0F15F
depends:        dlm
retpoline:      Y
name:           scst
vermagic:       5.13.4 SMP mod_unload modversions 
sig_id:         PKCS#7
signer:         SCST Kernel Modules
sig_key:        0A:9C:93:16:35:5A:4D:84:93:9B:45:05:3F:4E:50:A1:D2:4F:C9:21
sig_hashalgo:   sha512
signature:      8A:04:B4:3C:68:F0:27:EB:AF:95:D4:96:F1:51:64:66:44:B6:16:EF:
		E9:26:A3:5E:AA:A1:18:A8:53:2B:6F:D4:98:FC:3B:C8:1B:D6:5D:5D:
		E1:A7:3B:57:35:1E:45:18:B8:30:3A:8C:87:91:30:0D:AF:FF:B2:2A:
		87:35:4B:69:89:E2:BD:E1:1E:C0:2B:4A:91:97:2D:D0:3C:44:D3:2A:
		83:CA:0E:CF:93:79:47:8A:57:0E:DE:6A:DC:B0:6B:93:4B:84:1F:43:
		CA:7F:4A:11:AB:6E:85:DA:6B:64:BC:65:1F:D1:D7:60:D0:57:5C:70:
		ED:8F:4B:29:2F:E5:57:0F:D2:7B:03:04:E2:4F:D2:E4:85:13:C6:F4:
		76:31:5D:14:D9:C4:94:86:CB:97:7E:20:2B:8A:33:3D:A8:FF:2A:A7:
		4C:81:63:46:D8:63:1A:66:DB:B7:6D:C4:E9:B5:10:DB:BD:A6:03:7A:
		32:9F:3B:9B:B6:9A:ED:B7:04:BB:7B:DA:0F:D4:35:7B:0E:C5:D6:06:
		F6:20:64:53:6B:CE:EE:24:85:EC:98:AD:CC:A6:95:45:DF:E0:F7:BB:
		3E:83:A0:AB:39:31:6D:0A:8D:B9:82:64:46:77:DB:F3:58:7F:81:3B:
		10:E2:BF:A3:58:E0:24:41:5D:4E:77:6E:5C:C7:55:F2:CB:E0:45:C5:
		2E:12:D7:0C:67:55:06:B9:5A:B3:64:8C:C9:38:20:7E:B8:EB:B9:71:
		A2:46:FC:A0:17:E6:4E:B5:7B:C1:BF:EA:35:52:BD:20:50:BE:3F:96:
		F4:34:15:32:EB:9A:6F:55:34:FD:A2:D5:68:5D:11:16:D2:14:C3:04:
		6C:A5:52:1A:3C:F1:1E:B7:F8:4A:3F:B4:7C:CF:B4:96:D7:32:46:4F:
		31:A3:03:75:5A:FE:10:93:48:FF:F9:8F:D8:D8:6F:1A:96:FA:33:24:
		4D:B5:E1:A3:F8:79:CA:25:DF:51:FA:E2:86:89:FC:D2:FC:55:F4:C6:
		F8:65:27:E5:F4:6C:DA:83:AC:E2:52:C0:7B:7A:5C:01:77:B2:FD:D7:
		65:49:79:CD:C1:44:E6:A0:78:34:6B:35:40:65:DD:05:86:5F:0D:89:
		F5:80:BF:24:63:A9:15:C7:0F:2D:62:7A:6B:D6:F8:8B:DF:76:EF:F3:
		B2:9D:D2:D3:E7:AB:F5:36:CF:DF:8F:0F:B1:07:75:26:A7:1E:0C:3D:
		5A:BE:E5:18:D9:54:48:65:D3:89:23:79:BA:07:0E:DE:E9:98:64:7E:
		C4:DF:42:09:24:41:A2:F6:AC:FA:95:D4:E1:5E:DE:DA:E0:F7:39:42:
		3A:D6:C8:3C:50:6A:B7:B4:0B:C5:FF:E4
parm:           alua_invariant_check:Enables a run-time ALUA state invariant check. (bool)
parm:           scst_threads:SCSI target threads count (int)
parm:           scst_max_cmd_mem:Maximum memory allowed to be consumed by all SCSI commands of all devices at any given time in MB (int)
parm:           scst_max_dev_cmd_mem:Maximum memory allowed to be consumed by all SCSI commands of a device at any given time in MB (int)
parm:           forcibly_close_sessions:If enabled, close the sessions associated with an access control group (ACG) when an ACG is deleted via sysfs instead of returning -EBUSY (int)
'

Vermagic for module scst:

` 5.13.4 SMP mod_unload modversions `

Uname -r:

'5.13.4-051304-generic'

Installed libbpf0 is Version 0.3.2

As i found out with Kernel 5.11 was something wrong (i have currently Dwarf 1.20-1 installed, if this information is useful)

https://lore.kernel.org/bpf/CAJCQCtSQLc0VHqO4BY_-YB2OmCNNmHCS6fNdQKmMWGn2v=Jpdw@mail.gmail.com/T/

I have absolutely no idea where to start over. This is all information i could gather together

Thanks for your help !

Kind regards

**Comment by bvanassche** [comment]
Not sure what is going on. Will take a look.

**Comment by ASTuser1** [comment]
Thank you !

Meanwhile i have built the current git for testing purposes on Kernel 5.11.0-25 on another Machine - looks far better, Modules will get loaded entirely,  with the exception that the QLA2xxx 32-GBIT-Drivers won't find the Hardware through the Adress(es) of the QLA2464 Ports i have provided - even through they can be found manually.

Because i have  read somewhere that the 32GBIT Target Drivers could be responsible for this sort of trouble, i tried to build SCST with "QLA_32GBIT=no" Flag, but then it creates a separate Folder in lib/modules named "linux-5.11.22/extra" (which is way different from my 5.11.0-25--generic-Kernel and of course the correct lib/Modules Folder) and, by copying the generated "extra" folder to my current kernel libs, it complains about wrong/missing Symbols while Modprobe the QLA-Target-Module.

**Comment by bvanassche** [comment]
It may be necessary to run `depmod` after `make install` on Ubuntu. This is not necessary on any other Linux distro but is necessary on Ubuntu. I have not yet figured out why.

**Comment by ASTuser1** [comment]
Yep, i've done that several times on several occasions in between, doesn't help.

I have the slight suspicion that Ubuntu / Debian is not the best platform for SCST overall. Since the OS of the target machine has been fresh installed anyway, i'll consider to move to another distro. Can you recommend one?

Thanks !

**Comment by ASTuser1** [comment]
With Kernel 5.13.5:

"ERROR: modpost: "crc32c" [/home/bla/scst/scst/src/dev_handlers/scst_vdisk.ko] undefined! "

crc32c.h is located in /lib/modules/5.13.5/build/include/linux

**Comment by ASTuser1** [comment]
With 5.11.0-25: Symbols for qla2x00t (QLA16GB) wont get exported to modules-symbols. 

`[ 3653.590307] qla2x00tgt: Unknown symbol qla2x00_send_change_request (err -2)
[ 3653.590324] qla2x00tgt: Unknown symbol qla2xxx_tgt_register_driver (err -2)
[ 3653.590340] qla2x00tgt: Unknown symbol qla2x00_get_id_list (err -2)
[ 3653.590351] qla2x00tgt: Unknown symbol qla2x00_req_pkt (err -2)
[ 3653.590377] qla2x00tgt: Unknown symbol qla_clear_tgt_mode (err -2)
[ 3653.590403] qla2x00tgt: Unknown symbol qla2x00_wait_for_hba_online (err -2)
[ 3653.590441] qla2x00tgt: Unknown symbol qla2x00_get_port_database (err -2)
[ 3653.590453] qla2x00tgt: Unknown symbol qla2x00_issue_marker (err -2)
[ 3653.590468] qla2x00tgt: Unknown symbol qla2xxx_add_targets (err -2)
[ 3653.590490] qla2x00tgt: Unknown symbol qla2x00_start_iocbs (err -2)
[ 3653.590508] qla2x00tgt: Unknown symbol qla2x00_get_node_name_list (err -2)
[ 3653.590520] qla2x00tgt: Unknown symbol qla2xxx_tgt_unregister_driver (err -2)
[ 3653.590541] qla2x00tgt: Unknown symbol qla2x00_disable_tgt_mode (err -2)
[ 3653.590561] qla2x00tgt: Unknown symbol qla2x00_enable_tgt_mode (err -2)
`

Those Symbols are aliased in modules.symbols to qla2xxx_scst, not qla2x00tgt. So modprobe won t find the symbols for qla2x00tgt.

**Comment by bvanassche** [comment]
The answers to your questions are as follows:
* Most SCST users use CentOS 7 or 8. I'm using openSUSE Tumbleweed on my development system because it is a rolling distro that is pretty stable. Please note that a rolling distro is not for everyone.
* The SCST trunk builds and loads fine on my development system (kernel v5.13.4), including the 32-Gbit qla2x00tgt driver. However, port information shows up in the output of `grep -aH . /sys/class/fc_remote_ports/*/port_name` while the output of the command `ls /sys/kernel/scst_tgt/targets/qla2x00t/` is empty. That is a bug.
* crc32c is exported by the libcrc32c kernel module. Please verify whether `CONFIG_LIBCRC32C` is enabled in your kernel config.

**Comment by ASTuser1** [comment]
Good morning,

you are perfectly right, CONFIG_LIBCRC32 was indeed not set.

But i don't understand it at all, is why it was unconfigured, because i never touched this option via menuconfig or by editing the .config-File (after copy it from /boot) manually before compiling the Kernel.

Anyway, i've reinstalled 21.04, compiled 5.13.6, build SCST again with the 16GB-Driver, everything went smooth, even the symbol-errors were gone - and i think the reason was, because the qla2xxx_scst module was already loaded when i was trying to modprobe the QLA_TGT driver without reboot.  For any reason this seems to be the cause for the the symbol errors.

Well, so far, so good, i still have the problem that the Hardware-Adress of my QLA Target card (starting with 21:00:00) being not available, even with the 16GB driver. 

Many thanks !






I

**Comment by ASTuser1** [comment]
`targetAttributes(): Target 21:00:00:24:FF:2B:65:39 is not available`

but `cat /sys/class/fc_host/host*/port_name` shows

0x21000024ff2b6538
0x21000024ff2b6539

Both are unavailable.

This error was the main reason why i was trying to switch from the 32G-Driver to the 16G-Driver.

Many thanks !

**Comment by bvanassche** [comment]
Please share the output of `grep -aH . /sys/class/fc_remote_ports/*/port_name` (after the qla2x00tgt driver has been loaded).

**Comment by ASTuser1** [comment]
root@i5-2500:/usr/local/sbin# grep -aH . /sys/class/fc_remote_ports/*/port_name

grep: /sys/class/fc_remote_ports/*/port_name: Datei oder Verzeichnis nicht gefunden

**Comment by ASTuser1** [comment]
/sys/class/fc_remote_ports is entirely empty.

**Comment by ASTuser1** [comment]
lspci:

01:00.0 Fibre Channel: QLogic Corp. ISP2432-based 4Gb Fibre Channel to PCI Express HBA (rev 03)
01:00.1 Fibre Channel: QLogic Corp. ISP2432-based 4Gb Fibre Channel to PCI Express HBA (rev 03)

**Comment by ASTuser1** [comment]
lsmod:

qla2x00tgt             73728  0
qla2xxx_scst          417792  1 qla2x00tgt
nvme_fc                45056  0
nvme_fabrics           24576  1 nvme_fc
nvme_core             126976  2 nvme_fc,nvme_fabrics
sch_fq_codel           20480  2
scst_disk              16384  0
scst_user              53248  0
scst_vdisk            114688  0
libcrc32c              16384  1 scst_vdisk
hid_logitech_hidpp     45056  0
joydev                 28672  0
snd_hda_codec_hdmi     65536  1
snd_hda_codec_conexant    28672  1
snd_hda_codec_generic    81920  1 snd_hda_codec_conexant
input_leds             16384  0
ledtrig_audio          16384  1 snd_hda_codec_generic
hid_logitech_dj        28672  0
nls_iso8859_1          16384  1
snd_hda_intel          53248  2
snd_intel_dspcfg       28672  1 snd_hda_intel
snd_intel_sdw_acpi     20480  1 snd_intel_dspcfg
snd_hda_codec         147456  4 snd_hda_codec_generic,snd_hda_codec_conexant,snd_hda_codec_hdmi,snd_hda_intel
intel_rapl_msr         20480  0
intel_rapl_common      24576  1 intel_rapl_msr
x86_pkg_temp_thermal    20480  0
snd_hda_core           94208  5 snd_hda_codec_generic,snd_hda_codec_conexant,snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec
intel_powerclamp       20480  0
snd_hwdep              16384  1 snd_hda_codec
coretemp               20480  0
snd_pcm               118784  4 snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec,snd_hda_core
snd_seq_midi           20480  0
snd_seq_midi_event     16384  1 snd_seq_midi
kvm_intel             278528  0
i915                 2400256  10
snd_rawmidi            36864  1 snd_seq_midi
uas                    28672  0
kvm                   864256  1 kvm_intel
crct10dif_pclmul       16384  1
ghash_clmulni_intel    16384  0
hid_generic            16384  0
mei_hdcp               24576  0
usb_storage            73728  1 uas
drm_kms_helper        258048  1 i915
snd_seq                73728  2 snd_seq_midi,snd_seq_midi_event
cec                    53248  2 drm_kms_helper,i915
rc_core                57344  1 cec
aesni_intel           376832  0
crypto_simd            16384  1 aesni_intel
i2c_algo_bit           16384  1 i915
cryptd                 24576  2 crypto_simd,ghash_clmulni_intel
rapl                   20480  0
snd_seq_device         16384  3 snd_seq,snd_seq_midi,snd_rawmidi
wmi_bmof               16384  0
mei_me                 40960  1
serio_raw              20480  0
intel_cstate           20480  0
at24                   24576  0
snd_timer              40960  2 snd_seq,snd_pcm
usbhid                 57344  1 hid_logitech_dj
fb_sys_fops            16384  1 drm_kms_helper
mei                   131072  3 mei_hdcp,mei_me
syscopyarea            16384  1 drm_kms_helper
sysfillrect            16384  1 drm_kms_helper
sysimgblt              16384  1 drm_kms_helper
hid                   135168  4 usbhid,hid_generic,hid_logitech_dj,hid_logitech_hidpp
snd                    94208  15 snd_hda_codec_generic,snd_seq,snd_hda_codec_conexant,snd_seq_device,snd_hda_codec_hdmi,snd_hwdep,snd_hda_intel,snd_hda_codec,snd_timer,snd_pcm,snd_rawmidi
mac_hid                16384  0
soundcore              16384  1 snd
scsi_transport_fc      77824  1 qla2xxx_scst
scst                 3538944  4 qla2x00tgt,scst_disk,scst_user,scst_vdisk
dlm                   229376  1 scst
msr                    16384  0
parport_pc             45056  0
ppdev                  24576  0
lp                     20480  0
parport                69632  3 parport_pc,lp,ppdev
drm                   557056  10 drm_kms_helper,i915
ip_tables              32768  0
x_tables               49152  1 ip_tables
autofs4                45056  2
crc32_pclmul           16384  0
psmouse               159744  0
ahci                   40960  3
r8169                  90112  0
i2c_i801               36864  0
i2c_smbus              20480  1 i2c_i801
libahci                36864  1 ahci
lpc_ich                24576  0
realtek                32768  1
wmi                    32768  1 wmi_b

**Comment by bvanassche** [comment]
The above makes me wonder whether your QLogic adapter is recognized by the SCST drivers? Please share the output of `lspci -n | grep '^01:00'`.

**Comment by ASTuser1** [comment]
Got it, almost. The Initiator did not establish a link.

Target machine:

root@i5-2500:/sys/class/fc_host/host6# cat node_name && cat port_type && cat port_id && cat port_name && cat port_state && cat  symbolic_name && cat tgtid_bind_type && cat fabric_name
0x20000024ff2b6539
Point-To-Point (direct nport connection)
0x000002
0x21000024ff2b6539
Online
QLE2462 FW:v8.07.00 DVR:v8.04.00.05.2.2-SCST.03-k-p
wwpn (World Wide Port Name)
0xffffffff

For the Initiator (on the target machine)

root@i5-2500:/sys/class/fc_remote_ports/rport-6:0-0# cat node_name && cat port_id && cat port_name && cat port_state 
0x20000024ff2b669c
0x000001
0x21000024ff2b669c
Online

dmesg:

[    7.683323] [286]: qla2x00t: Initializing QLogic Fibre Channel HBA Driver target mode addon version 3.6.0-pre
[    7.683375] [286]: qla2x00t: Target mode driver for QLogic 2x00 controller registered successfully
[    7.683390] [286]: scst: Target template qla2x00t registered successfully
[    7.683415] [286]: scst: Target 21:00:00:24:ff:2b:65:38 for template qla2x00t registered successfully
[    7.683442] [286]: scst: Target 21:00:00:24:ff:2b:65:39 for template qla2x00t registered successfully
[    7.693943] [286]: scst: Virtual device handler vdisk_fileio for type 0 registered successfully
[    7.693951] [286]: scst: Virtual device handler vdisk_blockio for type 0 registered successfully
[    7.693954] [286]: scst: Virtual device handler vdisk_nullio for type 0 registered successfully
[    7.693958] [286]: scst: Virtual device handler vcdrom for type 5 registered successfully
[    7.700320] [286]: scst: Virtual device handler "scst_user" registered successfully
[    7.701531] [512]: scst_user: Cleanup thread started
[    7.703506] [286]: scst: Device handler "dev_disk" for type 0 registered successfully
[    7.703511] [286]: scst: Device handler "dev_disk_perf" for type 0 registered successfully
[    7.847062] alua: device handler registered
[    7.848256] emc: device handler registered
[    7.849653] rdac: device handler registered

if i get it correctly, the target is already registered, so scstadmin cannot get control over the target interface = "Target not available"= already in use, not "unavailable". Is this correct?

Sry for the fuss, this is the first time i ever had an FC card in my hands.

**Comment by ASTuser1** [comment]
Uh, i meant 

"if i get it correctly, the target is already registered, so scstadmin cannot get control over the target interface = "**Target does not exist**"= already in use, not "unavailable". Is this correct?

The "**Target does not exist**" comes every time when i try it to feed scstadmin with the scst.conf in /etc (but dmesg Output is the same with scst.conf removed from /etc)

**Comment by ASTuser1** [comment]
Could you explain  what in scst/stscadmin/scstadmin.sysfs/scstadm , Line 2756 happens? Does this mean that if when $is_virtual was one (Virtual driver=true, i suppose), it then gets false through "!" and then it throws the error? 

So could it be that `scstadmin -enable_target xx:xx:xx:xx:xx:xx:xx:xx -driver qla2x00t` "thinks" that i am trying to access a virtual device instead of an Hardware Target?

**Comment by bvanassche** [comment]
It's great news that the qla2x00tgt driver loads correctly and also that it recognizes the Fibre Channel ports :-) I recommend to proceed as follows:
* Run `modprobe qla2x00tgt; scstadmin -write_config /dev/stdout`
* Copy/paste the `TARGET_DRIVER qla2x00t` section to the end of /etc/scst.conf.
* Edit /etc/scst.conf as needed.

An example from my setup:
~~~
# modprobe qla2x00tgt; scstadmin -write_config /dev/stdout                   

Collecting current configuration: done.

Writing current configuration to file '/dev/stdout'.. # Automatically generated by SCST Configurator v3.5.0-pre.


TARGET_DRIVER copy_manager {
        TARGET copy_manager_tgt
}

TARGET_DRIVER qla2x00t {
        TARGET 21:00:00:24:ff:91:c4:14 {
                HW_TARGET

                enabled 0
        }

        TARGET 21:00:00:24:ff:91:c4:15 {
                HW_TARGET

                enabled 0
        }
}


All done.
~~~

**Comment by ASTuser1** [comment]
YYYESSSSS, success !  Initiatior finally finds LUN 0 at Boot (btw, i have changed "enabled" from 0 to 1). Well, that was hard work :-)

Great, really great ! 

Thank you so much for your effort !
Kind regards !

**Comment by ASTuser1** [comment]
Still having a small issue - initial copy speed is about 270 MB/Sec but then it drops rapidly down to 95/sec up to 115 MB/sec for a 16 GB File, using Midnight commander and Thunar, from SATA3-SSD to SSD, Sandy Bridge 4 Core to Haswell 4 Core, both Ext4, 

Gnome-Disk Utility shows about 276 to 284 MB Transfer rate for a Test File Size about 500 MB

Any optional settings to be made?

Thanks :-)

**Comment by bvanassche** [comment]
Information about how to tune performance is available in https://github.com/bvanassche/scst/blob/master/README.performance.

**Comment by ASTuser1** [comment]
Thank you :-)

It is a good transfer speed fot the moment; at least the target (mechanical) HDD reaches its maximum write speed (around 130 MB per Second ) . Since the SSD-HDD of the Target machine is fast, but anyway not really big at all (256 GB), i will later try to merge two mechanical 1 TB HDDs to a Fake-RAID0 (i know, i know....) and see if i can reach a continuous maximum transfer speed by copying.

**Comment by ASTuser1** [comment]
Sorry to interrupt you again - i know this "issue" is closed, but how can i get an actual file list on the Target machine, after i have copied files to it (Raid)?  

I've added a Target "scst_local", with lun 0 linked to my Raid, to scst.conf; it gives me now two "Raid" devices instead of one, but the copied files are not shown up until i reboot the target. 

Sorry again & many thanks !

**Comment by bvanassche** [comment]
Please do not mount a filesystem in read-write mode on top of scst_local - this is asking for data corruption. If you really need to see at the target side which files have been created from the initiator side without unmounting and remounting the filesystem then I think that you need a cluster filesystem, e.g. GFS2 or OCFS2.

**Comment by ASTuser1** [comment]
If i may add, because i've experienced a problem on another machine with another card: 

The reason for the message "Target is not available" is because the Target Name is case sensitive. So It doesnt help to the get the port numbers straight off the HBA Setup by pressing CTRL+Q and write them down - it relies on that what has been listed under sys/class/fc_host/host*/port_name .  

I think this is not correct, because these are hexadecimal numbers and should be converted at least always to upper case characters before handling them.

**Comment by bvanassche** [comment]
The origin of this behavior is that SCST uses sysfs as configuration interface and sysfs, just like other Linux filesystems, is case-sensitive. Anyway, if you would like to submit a patch to make SCST handle FC port names in a case-insensitive way I will take a look at it.

**Comment by ASTuser1** [comment]
This shouldn't be an attack. If it causes such problems, then one should just keep in mind, that the port names are always treated as they appear in sys/class/fc_host/host*/port_name. Maybe a simple hint like "please check port name for case sensitive letters" when a Target not found error is thrown,  would be enough. 

Or maybe by converting the input String (if it is handled as a string) once to upper and lower case and then check which of both are available.

**Comment by ASTuser1** [comment]
Well, scstadnim modified at line
2087 and onwards
2757 and onwards
2773 and onwards

in that way that it throws an additional Information. Maybe outputting a additional "cat" to sys/class/fc_host/host*/port_name would be nice in order to see the actual -required- port Name. 

I cannot implement that. I'm only in ASM for AVR, 8051, Cortex and more or less into Ruby.


[scstadmin.zip](https://github.com/bvanassche/scst/files/6949836/scstadmin.zip)
