### ISSUE TITLE
Unable to make connections after reboot

### ISSUE THREAD

**Issue by ASTuser1** [bvanassche/scst#44]
Hi,

after everything seems to be up and running - at least in case scstadmin has been fed with /etc/scst.conf and got triggered on the console- i am unable to make a connection from the Initiator to the Host,  after the host as been fully restarted and the client gets started afterwards.

Both, as already known, are equipped with Qlogic 2464 HBAs after the Host machine, running on Kernel 5.13.6).

The initiator seeks endless for available LUNs; they only become available, as told, if scst by scstadmin with --force on the console has been restarted.

According to dmesg on the host everything seems to be fine.  SCST claims the SCSI-Devices, the QLA-target mode is up and running, Targets (both connectors on the HBA) and (Virtual) device handlers are registered successfully. 

Of course scst.conf is also located on /etc and /etc/init.d (both identical) , "update-rc.d scst defaults" as well as "systemctl enable scst.service" has been performed.

Thank you for your help !

Kind regards

**Comment by bvanassche** [comment]
What operating system is running at the initiator side? It may be necessary to issue a LIP from the initiator side after the target has been rebooted. Instructions for Linux are available at https://www.thegeekdiary.com/when-to-use-rescan-scsi-bus-sh-i-lip-flag-in-centos-rhel/.

**Comment by ASTuser1** [comment]
Hi Bart,

thank your for your effort - unfortunaly, it didn't help. Initiator Side is Ubuntu 20.04. 

The LUNs won't get detected by the Client-HBA on pre-boot either, after the Host machine has been up and running and leaving it untouched. After SCST has been restarted manually on the host, the LUNS will get detected on the Initiator immediate. 

May i ask how your dmesg looks like after reboot regarding scst? For me it looks fine, but maybe there could be some differences to look after.

Thank you :-)

**Comment by ASTuser1** [comment]
My dmesg concerning scst and qla2xxx straight after reboot - and after "systemctl restart scst" has been performed manually.

Btw: 8:0:0:0 is my LTO Tape drive.


Two things are worrying me: First that the qla2xxx driver seems to tell the HBA that it should behave like a network card (which should be according to RFC2625 fully ok), and that one or several -additional- calls of "systemctl restart scst" causes scst to unload all modules and removes all connections, but the service doesn't start again.

[

[   23.101455] qla2xxx_scst: loading out-of-tree module taints kernel.
[   23.101763] qla2xxx_scst: module verification failed: signature and/or required key missing - tainting kernel
[   23.103779] qla2xxx [0000:00:00.0]-0005: 
[   23.103781] QLogic Fibre Channel HBA Driver: 8.04.00.05.2.2-SCST.03-k-p.
[   23.104141] qla2xxx [0000:01:00.0]-001d: 
[   23.104142] Found an ISP2432 irq 16 iobase 0x00000000eb324b5d.
[   23.649353] scsi host10: qla2xxx
[   23.652213] qla2xxx [0000:01:00.0]-00fb:10: 
[   23.652220] QLogic QLE2462 - PCI-Express Dual Channel 4Gb Fibre Channel HBA.
[   23.652236] qla2xxx [0000:01:00.0]-00fc:10: 
[   23.652238] ISP2432: PCIe (2.5GT/s x1) @ 0000:01:00.0 hdma+ host#=10 fw=8.07.00 (9496).
[   23.652684] qla2xxx [0000:01:00.1]-001d: 
[   23.652686] Found an ISP2432 irq 17 iobase 0x000000003befe703.
[   24.000946] qla2xxx [0000:01:00.0]-505f:10: 
[   24.000951] Link is operational (4 Gbps).
[   24.045364] scsi host11: qla2xxx
[   24.048608] qla2xxx [0000:01:00.1]-00fb:11: 
[   24.048615] QLogic QLE2462 - PCI-Express Dual Channel 4Gb Fibre Channel HBA.
[   24.048631] qla2xxx [0000:01:00.1]-00fc:11: 
[   24.048633] ISP2432: PCIe (2.5GT/s x1) @ 0000:01:00.1 hdma+ host#=11 fw=8.07.00 (9496).

[   25.681505] st 8:0:0:0: Power-on or device reset occurred

[   29.542204] [405]: scst: Attached to scsi2, channel 0, id 0, lun 0, type 0
[   29.542273] [405]: scst: Attached to scsi3, channel 0, id 0, lun 0, type 0
[   29.542303] [405]: scst: Attached to scsi4, channel 0, id 0, lun 0, type 0
[   29.542335] [405]: scst: Attached to scsi8, channel 0, id 0, lun 0, type 1
[   29.542967] [727]: scst: Init thread started
[   29.543011] [728]: scst: Task management thread started
[   29.543048] [729]: scst: Management thread started
[   29.543053] [405]: scst: Target template copy_manager registered successfully
[   29.543083] [405]: scst: Target copy_manager_tgt for template copy_manager registered successfully
[   29.543111] [405]: scst: Using security group "copy_manager_tgt" for initiator "copy_manager_sess" (target copy_manager_tgt)
[   29.543159] [405]: scst: SCST version 3.6.0-pre loaded successfully (global max mem for commands ignored, per device 579MB)
[   29.543162] [405]: scst: Enabled features: TRACING
[   29.606086] [405]: qla2x00t: Initializing QLogic Fibre Channel HBA Driver target mode addon version 3.6.0-pre
[   29.606158] [405]: qla2x00t: Target mode driver for QLogic 2x00 controller registered successfully
[   29.606166] [405]: scst: Target template qla2x00t registered successfully
[   29.606209] [405]: scst: Target 21:00:00:1b:32:91:41:5c for template qla2x00t registered successfully
[   29.606238] [405]: scst: Target 21:01:00:1b:32:b1:41:5c for template qla2x00t registered successfully
[   29.665040] [405]: scst: Target template scst_local registered successfully
[   29.665218] [405]: scst: Target scst_local_tgt for template scst_local registered successfully
[   29.665231] [405]: scst: Using security group "scst_local_tgt" for initiator "scst_local_host" (target scst_local_tgt)
[   29.665477] scsi host12: scst_local
[   29.775411] [405]: scst: Virtual device handler vdisk_fileio for type 0 registered successfully
[   29.775424] [405]: scst: Virtual device handler vdisk_blockio for type 0 registered successfully
[   29.775432] [405]: scst: Virtual device handler vdisk_nullio for type 0 registered successfully
[   29.775440] [405]: scst: Virtual device handler vcdrom for type 5 registered successfully
[   29.793455] [405]: scst: Virtual device handler "scst_user" registered successfully
[   29.793680] [733]: scst_user: Cleanup thread started
[   29.814228] [405]: scst: Device handler "dev_disk" for type 0 registered successfully
[   29.814239] [405]: scst: Device handler "dev_disk_perf" for type 0 registered successfully
[   29.838034] [405]: scst: Device handler "dev_tape" for type 1 registered successfully
[   29.838044] [405]: scst: Device handler "dev_tape_perf" for type 1 registered successfully
[   34.433225] loop0: detected capacity change from 0 to 8
[   36.473219] kauditd_printk_skb: 14 callbacks suppressed
[   36.473225] audit: type=1400 audit(1629061161.552:26): apparmor="DENIED" operation="capable" profile="/usr/sbin/cupsd" pid=845 comm="cupsd" capability=12  capname="net_admin"
[   37.314033] audit: type=1400 audit(1629061162.392:27): apparmor="DENIED" operation="capable" profile="/usr/sbin/cups-browsed" pid=952 comm="cups-browsed" capability=23  capname="sys_nice"
[   38.950023] e1000e 0000:00:19.0 enp0s25: NIC Link is Up 1000 Mbps Full Duplex, Flow Control: Rx/Tx
[   38.950175] IPv6: ADDRCONF(NETDEV_CHANGE): enp0s25: link becomes ready
[   46.565197] qla2xxx [0000:01:00.1]-8038:11: 
[   46.565203] Cable is unplugged...
[   71.162019] qla2xxx [0000:01:00.0]-505f:10: 
[   71.162024] Link is operational (4 Gbps).
[   75.150614] qla2xxx [0000:01:00.0]-505f:10: 
[   75.150621] Link is operational (4 Gbps).
[   79.214523] qla2xxx [0000:01:00.0]-505f:10: 
[   79.214529] Link is operational (4 Gbps).
[   83.278999] qla2xxx [0000:01:00.0]-505f:10: 
[   83.279005] Link is operational (4 Gbps).
[   87.343434] qla2xxx [0000:01:00.0]-505f:10: 
[   87.343440] Link is operational (4 Gbps).
[   91.407919] qla2xxx [0000:01:00.0]-505f:10: 
[   91.407925] Link is operational (4 Gbps).
[   95.472352] qla2xxx [0000:01:00.0]-505f:10: 
[   95.472358] Link is operational (4 Gbps).
[   99.536751] qla2xxx [0000:01:00.0]-505f:10: 
[   99.536757] Link is operational (4 Gbps).
[  103.601269] qla2xxx [0000:01:00.0]-505f:10: 
[  103.601275] Link is operational (4 Gbps).
[  107.665556] qla2xxx [0000:01:00.0]-505f:10: 
[  107.665561] Link is operational (4 Gbps).
[  111.730126] qla2xxx [0000:01:00.0]-505f:10: 
[  111.730132] Link is operational (4 Gbps).
[  115.794628] qla2xxx [0000:01:00.0]-505f:10: 
[  115.794634] Link is operational (4 Gbps).
[  119.859061] qla2xxx [0000:01:00.0]-505f:10: 
[  119.859066] Link is operational (4 Gbps).


; *********************RESTARTING SCST SERVICE ***********************************


[  120.284470] [2702]: qla2x00t: Unloading QLogic Fibre Channel HBA Driver target mode addon driver
[  120.284520] [2702]: scst: Waiting for 1 active commands to complete...
[  120.329070] [2702]: scst: All active commands completed
[  120.329112] [2702]: scst: Target 21:00:00:1b:32:91:41:5c for template qla2x00t unregistered successfully
[  120.329148] [2702]: scst: Waiting for 1 active commands to complete...
[  120.373068] [2702]: scst: All active commands completed
[  120.373097] [2702]: scst: Target 21:01:00:1b:32:b1:41:5c for template qla2x00t unregistered successfully
[  120.373107] [2702]: scst: Target template qla2x00t unregistered successfully
[  120.569119] [2714]: scst: Waiting for 1 active commands to complete...
[  120.605078] [2714]: scst: All active commands completed
[  120.605124] [2714]: scst: Target scst_local_tgt for template scst_local unregistered successfully
[  120.605212] [2714]: scst: Target template scst_local unregistered successfully
[  120.636487] [2715]: scst: Waiting for 1 active commands to complete...
[  120.669075] [2715]: scst: All active commands completed
[  120.669113] [2715]: scst: Device handler "dev_disk_perf" for type 0 unloaded
[  120.669116] [2715]: scst: Waiting for 1 active commands to complete...
[  120.705081] [2715]: scst: All active commands completed
[  120.705112] [2715]: scst: Device handler "dev_disk" for type 0 unloaded
[  120.748313] [2716]: scst: Waiting for 1 active commands to complete...
[  120.785083] [2716]: scst: All active commands completed
[  120.785115] [2716]: scst: Device handler "dev_tape_perf" for type 1 unloaded
[  120.785118] [2716]: scst: Waiting for 1 active commands to complete...
[  120.825107] [2716]: scst: All active commands completed
[  120.825154] [2716]: scst: Device handler "dev_tape" for type 1 unloaded
[  120.862124] [733]: scst_user: Cleanup thread finished
[  120.862274] [2719]: scst: Device handler "scst_user" unloaded
[  120.889632] [2720]: scst: Device handler "vdisk_nullio" unloaded
[  120.889644] [2720]: scst: Device handler "vdisk_blockio" unloaded
[  120.889651] [2720]: scst: Device handler "vdisk_fileio" unloaded
[  120.889658] [2720]: scst: Device handler "vcdrom" unloaded
[  120.969188] [2720]: scst: Waiting for 1 active commands to complete...
[  121.001077] [2720]: scst: All active commands completed
[  121.001123] [2720]: scst: Target copy_manager_tgt for template copy_manager unregistered successfully
[  121.001133] [2720]: scst: Target template copy_manager unregistered successfully
[  121.001235] [728]: scst: Task management thread finished
[  121.001261] [729]: scst: Management thread finished
[  121.001287] [727]: scst: Init thread finished
[  121.001308] [2720]: scst: Detached from scsi2, channel 0, id 0, lun 0, type 0
[  121.025146] [2720]: scst: Detached from scsi3, channel 0, id 0, lun 0, type 0
[  121.045089] [2720]: scst: Detached from scsi4, channel 0, id 0, lun 0, type 0
[  121.069091] [2720]: scst: Detached from scsi8, channel 0, id 0, lun 0, type 1
[  121.337286] [2720]: scst: Exiting SCST sysfs hierarchy...
[  124.429132] [722]: scst: User interface thread finished
[  124.429152] [2720]: scst: Exiting SCST sysfs hierarchy done
[  124.449962] [2720]: scst: SCST unloaded
[  124.546782] DLM installed
[  124.746640] [2740]: scst: Attached to scsi2, channel 0, id 0, lun 0, type 0
[  124.746672] [2740]: scst: Attached to scsi3, channel 0, id 0, lun 0, type 0
[  124.746699] [2740]: scst: Attached to scsi4, channel 0, id 0, lun 0, type 0
[  124.746704] [2742]: scst: User interface thread started
[  124.746724] [2740]: scst: Attached to scsi8, channel 0, id 0, lun 0, type 1
[  124.747088] [2747]: scst: Init thread started
[  124.747116] [2748]: scst: Task management thread started
[  124.747143] [2749]: scst: Management thread started
[  124.747149] [2740]: scst: Target template copy_manager registered successfully
[  124.747175] [2740]: scst: Target copy_manager_tgt for template copy_manager registered successfully
[  124.747194] [2740]: scst: Using security group "copy_manager_tgt" for initiator "copy_manager_sess" (target copy_manager_tgt)
[  124.747241] [2740]: scst: SCST version 3.6.0-pre loaded successfully (global max mem for commands ignored, per device 579MB)
[  124.747244] [2740]: scst: Enabled features: TRACING
[  124.751734] [2750]: scst: Device handler "dev_tape" for type 1 registered successfully
[  124.751746] [2750]: scst: Device handler "dev_tape_perf" for type 1 registered successfully
[  124.759306] [2751]: scst: Virtual device handler vdisk_fileio for type 0 registered successfully
[  124.759317] [2751]: scst: Virtual device handler vdisk_blockio for type 0 registered successfully
[  124.759325] [2751]: scst: Virtual device handler vdisk_nullio for type 0 registered successfully
[  124.759331] [2751]: scst: Virtual device handler vcdrom for type 5 registered successfully
[  124.948116] qla2xxx [0000:00:00.0]-0005: 
[  124.948121] QLogic Fibre Channel HBA Driver: 8.04.00.05.2.2-SCST.03-k-p.
[  124.948486] qla2xxx [0000:01:00.0]-001d: 
[  124.948488] Found an ISP2432 irq 16 iobase 0x0000000059bc8fc1.
[  125.333298] scsi host10: qla2xxx
[  125.336504] qla2xxx [0000:01:00.0]-00fb:10: 
[  125.336511] QLogic QLE2462 - PCI-Express Dual Channel 4Gb Fibre Channel HBA.
[  125.336529] qla2xxx [0000:01:00.0]-00fc:10: 
[  125.336530] ISP2432: PCIe (2.5GT/s x1) @ 0000:01:00.0 hdma+ host#=10 fw=8.07.00 (9496).
[  125.337034] qla2xxx [0000:01:00.1]-001d: 
[  125.337036] Found an ISP2432 irq 17 iobase 0x00000000a61947da.
[  125.725312] scsi host11: qla2xxx
[  125.728661] qla2xxx [0000:01:00.1]-00fb:11: 
[  125.728669] QLogic QLE2462 - PCI-Express Dual Channel 4Gb Fibre Channel HBA.
[  125.728688] qla2xxx [0000:01:00.1]-00fc:11: 
[  125.728690] ISP2432: PCIe (2.5GT/s x1) @ 0000:01:00.1 hdma+ host#=11 fw=8.07.00 (9496).
[  126.345271] qla2xxx [0000:01:00.0]-505f:10: 
[  126.345278] Link is operational (4 Gbps).
[  129.965748] qla2xxx [0000:01:00.0]-505f:10: 
[  129.965754] Link is operational (4 Gbps).
[  130.766938] [2752]: qla2x00t: Initializing QLogic Fibre Channel HBA Driver target mode addon version 3.6.0-pre
[  130.767035] [2752]: qla2x00t: Target mode driver for QLogic 2x00 controller registered successfully
[  130.767045] [2752]: scst: Target template qla2x00t registered successfully
[  130.767090] [2752]: scst: Target 21:00:00:1b:32:91:41:5c for template qla2x00t registered successfully
[  130.767134] [2752]: scst: Target 21:01:00:1b:32:b1:41:5c for template qla2x00t registered successfully
[  130.787730] [2771]: scst: Target template scst_local registered successfully
[  130.787871] [2771]: scst: Target scst_local_tgt for template scst_local registered successfully
[  130.787898] [2771]: scst: Using security group "scst_local_tgt" for initiator "scst_local_host" (target scst_local_tgt)
[  130.788192] scsi host12: scst_local
[  131.063364] [2742]: scst: Removed all devices from group copy_manager_tgt
[  131.066567] [2742]: scst: Removed all devices from group 21:00:00:1b:32:91:41:5c
[  131.069627] [2742]: scst: Removed all devices from group 21:01:00:1b:32:b1:41:5c
[  131.072644] [2742]: scst: Removed all devices from group scst_local_tgt
[  132.083057] [2742]: scst: Waiting for 1 active commands to complete...
[  132.121203] [2742]: scst: All active commands completed
[  132.121254] [2742]: scst: Target scst_local_tgt for template scst_local unregistered successfully
[  132.318603] [2742]: dev_tape: ***WARNING***: Unit not ready: 8000002
[  132.324087] [2742]: scst: Device 8:0:0:0: TST 0, TMF_ONLY 0, QUEUE ALG 0, QErr 0, SWP 0, TAS 0, D_SENSE 0, DPICZ 0, has_own_order_mgmt 1
[  132.324108] [2742]: scst: Device 8:0:0:0 assigned to dev handler dev_tape
[  132.324443] [2742]: dev_vdisk: Registering virtual vdisk_blockio device q6600_raid (BLOCKIO, ROTATIONAL)
[  132.324719] [2742]: dev_vdisk: Attached SCSI target virtual disk q6600_raid (file="/dev/mapper/isw_dghijfhcei_Volume0p3", fs=457242MB, bs=512, nblocks=936431616, cyln=457242)
[  132.333260] [2742]: scst: Added device q6600_raid to group copy_manager_tgt (LUN 0, flags 0x4) to target copy_manager_tgt
[  132.333283] [2742]: scst: Attached to virtual device q6600_raid (id 1)
[  132.339479] [2742]: scst: Waiting for 1 active commands to complete...
[  132.373227] [2742]: scst: All active commands completed
[  132.373504] [2742]: scst: Added device q6600_raid to group test (LUN 0, flags 0x2) to target 21:00:00:1b:32:91:41:5c
[  132.373684] [2742]: scst: Added device 8:0:0:0 to group test (LUN 1, flags 0x2) to target 21:00:00:1b:32:91:41:5c
[  132.374481] [2742]: scst: Waiting for 1 active commands to complete...
[  132.409207] [2742]: scst: All active commands completed
[  132.409215] [2742]: scst: Added name 21:00:00:24:FF:2B:66:9C to group test (target 21:00:00:1b:32:91:41:5c)
[  132.409398] [2742]: scst: Waiting for 1 active commands to complete...
[  132.441206] [2742]: scst: All active commands completed
[  132.441214] [2742]: scst: Added name 21:00:00:24:FF:2B:66:9D to group test (target 21:00:00:1b:32:91:41:5c)
[  132.444507] [2742]: scst: Waiting for 1 active commands to complete...
[  132.477214] [2742]: scst: All active commands completed
[  132.477447] [2742]: scst: Added device q6600_raid to group test2 (LUN 0, flags 0x2) to target 21:01:00:1b:32:b1:41:5c
[  132.477636] [2742]: scst: Added device 8:0:0:0 to group test2 (LUN 1, flags 0x2) to target 21:01:00:1b:32:b1:41:5c
[  132.478306] [2742]: scst: Waiting for 1 active commands to complete...
[  132.513208] [2742]: scst: All active commands completed
[  132.513218] [2742]: scst: Added name 21:00:00:24:FF:2B:65:39 to group test2 (target 21:01:00:1b:32:b1:41:5c)
[  132.513727] [2742]: scst: Target scst_local for template scst_local registered successfully
[  132.513752] [2742]: scst: Using security group "scst_local" for initiator "scst_local" (target scst_local)
[  132.514044] scsi host12: scst_local
[  132.533488] [2742]: scst: Added device q6600_raid to group scst_local (LUN 0, flags 0x2) to target scst_local
[  132.533713] scsi 12:0:0:0: Direct-Access     SCST_BIO q6600_raid       360  PQ: 0 ANSI: 6
[  132.533760] [2742]: scst: Added device 8:0:0:0 to group scst_local (LUN 1, flags 0x2) to target scst_local
[  132.533772] [138]: scst_local: Configuring queue depth 64 on sdev 000000005f944663 (tagged supported 1)
[  132.534291] sd 12:0:0:0: Attached scsi generic sg4 type 0
[  132.534441] sd 12:0:0:0: Power-on or device reset occurred
[  132.535005] sd 12:0:0:0: [sdd] 936431616 512-byte logical blocks: (479 GB/447 GiB)
[  132.535040] sd 12:0:0:0: [sdd] Write Protect is off
[  132.535043] sd 12:0:0:0: [sdd] Mode Sense: 83 00 10 08
[  132.535091] sd 12:0:0:0: [sdd] Write cache: enabled, read cache: enabled, supports DPO and FUA
[  132.535148] sd 12:0:0:0: [sdd] Optimal transfer size 393216 bytes
[  132.535402] scsi 12:0:0:1: Sequential-Access HP       Ultrium 2-SCSI   F6AA PQ: 0 ANSI: 3
[  132.535411] [138]: scst_local: Configuring queue depth 64 on sdev 0000000042d46841 (tagged supported 0)
[  132.536210] st 12:0:0:1: Attached scsi tape st1
[  132.536215] st 12:0:0:1: st1: try direct i/o: yes (alignment 4096 B)
[  132.536399] st 12:0:0:1: Attached scsi generic sg5 type 1
[  132.557993] sd 12:0:0:0: [sdd] Attached SCSI disk
[  132.562552] [2742]: scst: Using autogenerated relative target id 1 for target 21:00:00:1b:32:91:41:5c
[  132.562560] [2742]: qla2x00t(10): Enabling target mode
[  132.562580] [2742]: qla2x00t(10): session for wwn 21:00:00:24:ff:2b:66:9c (loop_id 0, s_id 0:0:ef, confirmed completion supported) added
[  132.562585] [2749]: scst: Using security group "test" for initiator "21:00:00:24:ff:2b:66:9c" (target 21:00:00:1b:32:91:41:5c)
[  132.562599] qla2xxx [0000:01:00.0]-00af:10: 
[  132.562604] Performing ISP error recovery - ha=000000002bdc87dc.
[  132.562778] [2755]: qla2x00t(10): session for port 21:00:00:24:ff:2b:66:9c (loop_id 0) scheduled for deletion in 50 secs
[  132.574643] st 12:0:0:1: Power-on or device reset occurred
[  132.578175] [2964]: scst: Command finished with CHECK CONDITION, but without sense data (opcode TEST UNIT READY), issuing REQUEST SENSE
[  132.580307] [2964]: scst: ***WARNING***: REQUEST SENSE returned NO SENSE (orig cmd TEST UNIT READY)
[  132.601572] qla2xxx [0000:01:00.0]-1073:10: 
[  132.601575] Disabling FC tape support
[  133.453230] [2755]: qla2x00t(10): LIP reset occurred
[  134.541235] [2755]: qla2x00t(10): LIP occurred
[  134.561234] [2755]: qla2x00t(10): Loop up occurred
[  134.581234] qla2xxx [0000:01:00.0]-505f:10: 
[  134.581237] Link is operational (4 Gbps).
[  134.641239] [2755]: qla2x00t(10): LIP reset (loop 0xffff), subcode 2
[  134.821232] [94]: qla2x00t(10): RSCN registration failed: 0x2 (OK for non-fabric setups)
[  135.632894] [2742]: scst: Using autogenerated relative target id 2 for target 21:01:00:1b:32:b1:41:5c
[  135.632901] [2742]: qla2x00t(11): Enabling target mode
[  138.701071] EXT4-fs (sdd): 2 orphan inodes deleted
[  138.701081] EXT4-fs (sdd): recovery complete
[  138.782758] EXT4-fs (sdd): mounted filesystem with ordered data mode. Opts: (null). Quota mode: none.
[  148.237379] qla2xxx [0000:01:00.1]-8038:11: 
[  148.237385] Cable is unplugged...
[  149.261356] qla2xxx [0000:01:00.1]-00af:11: 
[  149.261359] Performing ISP error recovery - ha=00000000b3ef68f4.
[  149.300250] qla2xxx [0000:01:00.1]-1073:11: 
[  149.300252] Disabling FC tape support
[  169.761468] qla2xxx [0000:01:00.1]-8038:11: 
[  169.761473] Cable is unplugged...
[  186.642058] [0]: qla2x00t(10): Loop down occurred
[  186.644721] [0]: qla2x00t(10): Link failure detected
[  186.644727] [0]: qla2x00t(10): session for port 21:00:00:24:ff:2b:66:9c (loop_id 0) scheduled for deletion in 50 secs
[  193.805542]  rport-10:0-0: blocked FC remote port time out: removing rport
[  212.942098] [0]: qla2x00t(10): LIP reset occurred
[  212.942124] [0]: qla2x00t(10): LIP reset (loop 0xffff), subcode 2
[  213.023067] [0]: qla2x00t(10): LIP occurred
[  213.027237] [0]: qla2x00t(10): Loop up occurred
[  213.027269] qla2xxx [0000:01:00.0]-505f:10: 
[  213.027271] Link is operational (4 Gbps).
[  213.028327] [136]: qla2x00t(10): RSCN registration failed: 0x2 (OK for non-fabric setups)
[  228.445736] [0]: qla2x00t(10): Loop down occurred
[  228.448392] [0]: qla2x00t(10): Link failure detected
[  228.448398] [0]: qla2x00t(10): session for port 21:00:00:24:ff:2b:66:9c (loop_id 0) scheduled for deletion in 50 secs
[  229.082656] [0]: qla2x00t(10): LIP reset occurred
[  229.082684] [819]: qla2x00t(10): LIP reset (loop 0xffff), subcode 2
[  229.131631] [0]: qla2x00t(10): LIP occurred
[  229.135196] [0]: qla2x00t(10): Loop up occurred
[  229.135244] qla2xxx [0000:01:00.0]-505f:10: 
[  229.135247] Link is operational (4 Gbps).
[  229.136381] [136]: qla2x00t(10): RSCN registration failed: 0x2 (OK for non-fabric setups)

**Comment by ASTuser1** [comment]
Forgive me if i am wrong, I have the slight suspicion that "/etc/init.d/scst start", according to "service scst status", wont be called a boot time - or runs through the scst script without executing anything, because it even does not throw any messaged to stdout like "Already running" when performing a "service scst start". 

The dmesg-messages on boot time regarding to scst are thrown by the scst modules, which were added manually to /etc/modules.

I have no idea if the scst Kernel-Module grabs end enables at boot time the configuration file under /etc/scst.conf, or if this is a job which should be performed afterwards by a systemd-call to  "/etc/init.d/scst" at boot time.

**Comment by ASTuser1** [comment]
Success - adding the scst-Modules manually to /etc/modules caused the problem. So the widespread "how to compile and use scst" examples, in which they say, that one has to add the scst device drivers and modules manually to /etc/modules is simply wrong - at least for my Ubuntu 20.04.
