### ISSUE TITLE
compilation error on kernel 5.14

### ISSUE THREAD

**Issue by limbo127** [bvanassche/scst#47]
Hello, 
Some compilations errors with the new stable linux kernel 5.14 
- remove REQ_OP_SCSI_{IN,OUT}
- status-byte
...

Regards, 
Nicolas

**Comment by bvanassche** [comment]
The SCST core and also the iSCSI, iSER and SRP target drivers have just been ported to kernel v5.14. The QLogic target drivers will follow soon.

**Comment by limbo127** [comment]
Thanks a lot.
Nicolas

Le ven. 3 sept. 2021 à 07:36, Bart Van Assche ***@***.***> a
écrit :

**Comment by bvanassche** [comment]
More fixes have been checked in on the trunk and the master branch. Please reopen this bug report if there would be any remaining issues related to building SCST against kernel v5.14.
