### ISSUE TITLE
git-based package versioning scheme is not rpm upgrade friendly

### ISSUE THREAD

**Issue by bprotopopov** [bvanassche/scst#5]
When the code is built from a git repo, the git hash (as in ```git show```) of the commit is appended to the version of the RPMs. However, since the commit hashes are not guaranteed be "monotonically increasing" from the RPM tools standpoint (as opposed to straight incrementing numbers, for instance), RPM packages built off more recent hashes are not guaranteed to upgrade packages built off the eralier hashes. 

One solution here is to use git tags (to tag commits that bump versions in the code) along with ```git describe``` to guarantee that the versions are in fact increasing. Also, other projects put the hash info in the release as opposed to version, but that is debatable.

**Comment by bvanassche** [comment]
This should have been fixed more than six months ago. Can you have a look at patch "scst.spec: Make version numbers monotonically increasing for the git tree" (https://github.com/bvanassche/scst/commit/6c6a6e6ba3a8ea17bbe18f89f8e107557ce89f6b)?

**Comment by bprotopopov** [comment]
@bvanassche, yes, the 6c6a6e6 seems to be doing it, I was looking at the earlier code. I'll close the bug.

**Comment by bprotopopov** [comment]
The approach with using rNNN where NNN is a number of commits on the branch does not quite address the case of transitioning from the old versioning scheme to the new one. 

RPM version comparison is a bit unusual in that it does not use strcmp() or the like, but has its own rules. The rpmdev-vercmp from rpmdevtools can help: 
```
$ rpmdev-vercmp scst-2.6.32-573.12.1.el6.x86_64-devel-3.0.1.r110-1.x86_64 scst-2.6.32-573.12.1.el6.x86_64-devel-3.0.1.5a99aca-1
0:scst-2.6.32-573.12.1.el6.x86_64-devel-3.0.1.5a99aca-1 is newer
```
It is my understanding that the 'all number' version is always greater than 'version with some chars in it'. So, I recommend removing the 'r' 
```
$ rpmdev-vercmp scst-2.6.32-573.12.1.el6.x86_64-devel-3.0.1.110-1.x86_64 scst-2.6.32-573.12.1.el6.x86_64-devel-3.0.1.5a99aca-1
0:scst-2.6.32-573.12.1.el6.x86_64-devel-3.0.1.110-1.x86_64 is newer
```

**Comment by bvanassche** [comment]
The 'r' has been left out from the revision number of the scst and scstadmin RPMs. Please retest.
