### ISSUE TITLE
Debian 10 build error

### ISSUE THREAD

**Issue by sibersoft** [bvanassche/scst#52]
Hello

I'm trying to make package on Debian 10 kernel 4.19, error I get

make[2]: Leaving directory '/root/scst/scst/src'
make[1]: Leaving directory '/root/scst/scst'
make[1]: Entering directory '/root/scst/fcst'
/usr/bin/make -C /lib/modules/4.19.0-18-amd64/build M=/root/scst/fcst                          
make[2]: Entering directory '/usr/src/linux-headers-4.19.0-18-amd64'
  CC [M]  /root/scst/fcst/ft_cmd.o
  CC [M]  /root/scst/fcst/ft_io.o
/root/scst/fcst/ft_cmd.c: In function 'ft_send_response':
/root/scst/fcst/ft_cmd.c:264:2: error: implicit declaration of function 'fc_fill_fc_hdr'; did you mean 'fc_fill_hdr'? [-Werror=implicit-function-declaration]
  fc_fill_fc_hdr(fp, FC_RCTL_DD_CMD_STATUS, ep->did, ep->sid, FC_TYPE_FCP,
  ^~~~~~~~~~~~~~
  fc_fill_hdr
/root/scst/fcst/ft_io.c: In function 'ft_send_read_data':
/root/scst/fcst/ft_io.c:186:3: error: implicit declaration of function 'fc_fill_fc_hdr'; did you mean 'fc_fill_hdr'? [-Werror=implicit-function-declaration]
   fc_fill_fc_hdr(fp, FC_RCTL_DD_SOL_DATA, ep->did, ep->sid,
   ^~~~~~~~~~~~~~
   fc_fill_hdr
cc1: some warnings being treated as errors
make[5]: *** [/usr/src/linux-headers-4.19.0-18-common/scripts/Makefile.build:308: /root/scst/fcst/ft_io.o] Error 1
make[5]: *** Waiting for unfinished jobs....
cc1: some warnings being treated as errors
make[5]: *** [/usr/src/linux-headers-4.19.0-18-common/scripts/Makefile.build:308: /root/scst/fcst/ft_cmd.o] Error 1
make[4]: *** [/usr/src/linux-headers-4.19.0-18-common/Makefile:1561: _module_/root/scst/fcst] Error 2
make[3]: *** [Makefile:146: sub-make] Error 2
make[2]: *** [Makefile:8: all] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-4.19.0-18-amd64'
make[1]: *** [Makefile:63: all] Error 2
make[1]: Leaving directory '/root/scst/fcst'
make[1]: Entering directory '/root/scst'
cd scst && make 2debug
make[2]: Entering directory '/root/scst/scst'
make[2]: Leaving directory '/root/scst/scst'
make[1]: Leaving directory '/root/scst'
mv: cannot stat '/root/scst/debian/tmp/usr/man': No such file or directory
make: *** [debian/rules:58: install] Error 1
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -jauto failed
make: *** [Makefile:386: dpkg] Error 29`

**Comment by bvanassche** [comment]
Please reopen if the commit mentioned above wouldn't fix this.

**Comment by sibersoft** [comment]
Unfortunently it didn't helped still same error during build.

**Comment by sibersoft** [comment]
Hi, can't reopen issue 

----- Oryginalna wiadomość -----

Od: "Bart Van Assche" ***@***.***> 
Do: "bvanassche/scst" ***@***.***> 
DW: "sibersoft" ***@***.***>, "Author" ***@***.***> 
Wysłane: środa, 1 grudzień 2021 7:01:39 
Temat: Re: [bvanassche/scst] Debian 10 build error (Issue #52) 



Please reopen if the commit mentioned above wouldn't fix this. 
— 
You are receiving this because you authored the thread. 
Reply to this email directly, view it on GitHub , or unsubscribe . 
Triage notifications on the go with GitHub Mobile for iOS or Android .

**Comment by bvanassche** [comment]
The patch mentioned above fixes the build for Debian 11. I want to look into the Debian 10 issue but I'm not sure where to find a Debian 10 installer? I haven't found it on https://mirrors.kernel.org/debian-cd/

**Comment by sibersoft** [comment]
Here is link https://cdimage.debian.org/cdimage/archive/10.11.0/amd64/iso-cd/debian-10.11.0-amd64-netinst.iso

**Comment by bvanassche** [comment]
The commit mentioned above fixes the SCST build in my Debian 10 VM. Please let me know if that commit wouldn't be sufficient.

**Comment by sibersoft** [comment]
Works perfect thank you
