### ISSUE TITLE
Error occured if I try to build scst

### ISSUE THREAD

**Issue by narangel** [bvanassche/scst#9]
make[3]: Leaving directory `/usr/src/kernels/2.6.32-642.1.1.el6.x86_64'
make[2]: Leaving directory `/root/scst/scst/src'
make[1]: Leaving directory `/root/scst/scst'
make[1]: Entering directory `/root/scst/qla2x00t/qla2x00-target'
make BUILD_2X_MODULE=y CONFIG_SCSI_QLA2XXX_TARGET=y \
                SUBDIRS=/root/scst/qla2x00t/qla2x00-target/.. -C /root/scst/qla2x00                               t/qla2x00-target/.. all
make[2]: Entering directory `/root/scst/qla2x00t'
make -C /lib/modules/2.6.32-642.1.1.el6.x86_64/build SUBDIRS=/root/scst/qla2x00t BU                               ILD_INI=m EXTRA_CFLAGS="-Wextra -Wno-unused-parameter -Wno-missing-field-initialize                               rs -I/root/scst/qla2x00t/../scst/include -DCONFIG_SCSI_QLA2XXX_TARGET=y"
make[3]: Entering directory `/usr/src/kernels/2.6.32-642.1.1.el6.x86_64'
  LD      /root/scst/qla2x00t/built-in.o
  CC [M]  /root/scst/qla2x00t/qla_os.o
In file included from /root/scst/qla2x00t/qla_os.c:12:
include/linux/kthread.h:7: error: expected declaration specifiers or ‘...’ before ‘                               (’ token
include/linux/kthread.h:7: error: expected declaration specifiers or ‘...’ before ‘                               (’ token
include/linux/kthread.h:7: error: expected declaration specifiers or ‘...’ before ‘                               (’ token
include/linux/kthread.h:11: warning: function declaration isn’t a prototype
include/linux/kthread.h:13: error: conflicting types for ‘kthread_create’
include/linux/kthread.h:16: note: a parameter list with an ellipsis can’t match an                                empty parameter name list declaration
include/linux/kthread.h:7: note: previous declaration of ‘kthread_create’ was here
make[4]: *** [/root/scst/qla2x00t/qla_os.o] Error 1
make[3]: *** [_module_/root/scst/qla2x00t] Error 2
make[3]: Leaving directory `/usr/src/kernels/2.6.32-642.1.1.el6.x86_64'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/root/scst/qla2x00t'
make[1]: *** [qla2xxx_scst] Error 2
make[1]: Leaving directory `/root/scst/qla2x00t/qla2x00-target'
make: *** [all] Error 2

I got above error messages when I execute below command.

# BUILD_2X_MODULE=y CONFIG_SCSI_QLA_FC=y CONFIG_SCSI_QLA2XXX_TARGET=y make all install

I am testing this on CentOS 6.9.
anyone who has any idea to solve this?

**Comment by bvanassche** [comment]
A fix has been checked in on the master branch. Please update your local copy of SCST and retest. Please also consider to use the "make rpm" method to build SCST as explained on https://github.com/bvanassche/scst/wiki/1-Installation.
